package org.hnau.pinfin.projector

import androidx.compose.runtime.Immutable

@Immutable
data class Localization(
    val appName: String,
    val comment: String,
    val entry: String,
    val transaction: String,
    val transactions: String,
    val analytics: String,
    val config: String,
    val newTransaction: String,
    val budgets: String,
    val transfer: String,
    val add: String,
    val amount: String,
    val date: String,
    val time: String,
    val type: String,
    val create: String,
    val searchCreate: String,
    val category: String,
    val addRecord: String,
    val noTransactions: String,
    val addTransaction: String,
    val account: String,
    val removeRecord: String,
    val yes: String,
    val no: String,
    val cancel: String,
    val close: String,
    val save: String,
    val notSave: String,
    val accounts: String,
    val categories: String,
    val saveChanges: String,
    val toBudgetsList: String,
    val budgetsSync: String,
    val startServer: String,
    val openClient: String,
    val address: String,
    val port: String,
    val syncServer: String,
    val syncServerIsActive: String,
    val addressesToConnect: String,
    val stop: String,
    val stopSyncServer: String,
    val budgetsToSynchronization: String,
    val errorWhileLoadingBudgetsListFromServer: String,
    val tryAgain: String,
    val thereIsNoBudgetsForSynchronization: String,
    val stopSync: String,
    val budgetSync: String,
    val budgetWasSynchronized: String,
    val errorWhileBudgetSynchronization: String,
    val back: String,
    val budgetName: String,
    val noBudgets: String,
    val createNewBudget: String,
    val createDemoBudget: String,
    val removeBudget: String,
    val removeTransaction: String,
    val categoriesNotFound: String,
    val accountsNotFound: String,
    val createNewCategory: String,
    val createNewAccount: String,
    val thereAreNoCategories: String,
    val thereAreNoAccounts: String,
    val selectIcon: String,
    val search: String,
    val noIconsFound: String,
    val accountSettings: String,
    val hideIfAmountIsZero: String,
    val name: String,
    val categorySettings: String,
    val hue: String,
    val icon: String,
    val records: String,
    val credits: String,
    val debits: String,
    val total: String,
) {

    companion object {

        val default = Localization(
            appName = "PinFin",
            comment = "Название",
            entry = "Транзакция",
            transaction = "Транзакция",
            transactions = "Транзакции",
            analytics = "Аналитика",
            config = "Настройки",
            newTransaction = "Новая транзакция",
            budgets = "Бюджеты",
            transfer = "Перевод",
            add = "Добавить",
            amount = "Сумма",
            date = "Дата",
            time = "Время",
            type = "Тип",
            create = "Создать",
            searchCreate = "Найти/создать",
            category = "Категория",
            addRecord = "Добавить запись",
            noTransactions = "Транзакции отсутствуют",
            addTransaction = "Добавить транзакцию",
            account = "Счёт",
            removeRecord = "Удалить запись?",
            yes = "Да",
            no = "Нет",
            cancel = "Отмена",
            close = "Закрыть",
            save = "Сохранить",
            notSave = "Не сохранять",
            accounts = "Счета",
            categories = "Категории",
            saveChanges = "Сохранить изменения?",
            toBudgetsList = "К списку бюджетов",
            budgetsSync = "Синхронизация бюджетов",
            startServer = "Запустить сервер",
            openClient = "Открыть клиент",
            address = "Адрес",
            port = "Порт",
            syncServer = "Сервер синхронизации",
            syncServerIsActive = "Сервер синхронизации запущен",
            addressesToConnect = "Адреса для подключения",
            stop = "Остановить",
            stopSyncServer = "Остановить сервер синхронизации",
            budgetsToSynchronization = "Бюджеты для синхронизации",
            errorWhileLoadingBudgetsListFromServer = "Ошибка загрузки бюджетов с сервера",
            tryAgain = "Попробовать снова",
            thereIsNoBudgetsForSynchronization = "Отсутствуют бюджеты для синхронизации",
            stopSync = "Остановить синхронизацию",
            budgetSync = "Синхронизация бюджета",
            budgetWasSynchronized = "Бюджет успешно синхронизирован",
            errorWhileBudgetSynchronization = "Ошибка синхронизации бюджета",
            back = "Назад",
            budgetName = "Название бюджета",
            noBudgets = "Бюджеты отсутствуют",
            createNewBudget = "Создать новый бюджет",
            createDemoBudget = "Создать Demo бюджет",
            removeBudget = "Удалить бюджет",
            removeTransaction = "Удалить транзакцию",
            categoriesNotFound = "Категории не найдены",
            accountsNotFound = "Счета не найдены",
            createNewCategory = "Создать новую категорию",
            createNewAccount = "Создать новый счёт",
            thereAreNoCategories = "Категории отсутствуют, введите название новой категории",
            thereAreNoAccounts = "Счета отсутствуют, введите название нового счёта",
            selectIcon = "Выберите иконку",
            search = "Поиск",
            noIconsFound = "Иконки по этим критериям не найдены",
            accountSettings = "Настройки счёта",
            hideIfAmountIsZero = "Скрывать при нулевом балансе",
            name = "Название",
            categorySettings = "Настройки категории",
            hue = "Цвет",
            icon = "Иконка",
            records = "Записи",
            credits = "Доходы",
            debits = "Расходы",
            total = "Всего",
        )
    }
}
