package org.hnau.pinfin.projector

import androidx.compose.runtime.Immutable

@Immutable
data class Localization(
    val appName: String = "PinFin",
    val comment: String = "Название",
    val entry: String = "Транзакция",
    val transaction: String = "Транзакция",
    val transactions: String = "Транзакции",
    val analytics: String = "Аналитика",
    val manage: String = "Управление",
    val newTransaction: String = "Новая транзакция",
    val budgets: String = "Бюджеты",
    val transfer: String = "Перевод",
    val add: String = "Добавить",
    val amount: String = "Сумма",
    val date: String = "Дата",
    val time: String = "Время",
    val type: String = "Тип",
    val create: String = "Создать",
    val searchCreate: String = "Найти/создать",
    val category: String = "Категория",
    val addRecord: String = "Добавить запись",
    val noTransactions: String = "Транзакции отсутствуют",
    val addTransaction: String = "Добавить транзакцию",
    val account: String = "Счёт",
    val removeRecord: String = "Удалить запись?",
    val yes: String = "Да",
    val no: String = "Нет",
    val cancel: String = "Отмена",
    val close: String = "Закрыть",
    val save: String = "Сохранить",
    val edit: String = "Редактировать",
    val reset: String = "Сбросить",
    val notSave: String = "Не сохранять",
    val accounts: String = "Счета",
    val categories: String = "Категории",
    val saveChanges: String = "Сохранить изменения?",
    val toBudgetsList: String = "К списку бюджетов",
    val back: String = "Назад",
    val budgetName: String = "Название бюджета",
    val noBudgets: String = "Бюджеты отсутствуют",
    val createNewBudget: String = "Создать новый бюджет",
    val createDemoBudget: String = "Создать Demo бюджет",
    val removeBudget: String = "Удалить бюджет",
    val removeTransaction: String = "Удалить транзакцию",
    val categoriesNotFound: String = "Категории не найдены",
    val accountsNotFound: String = "Счета не найдены",
    val createNewCategory: String = "Создать новую категорию",
    val createNewAccount: String = "Создать новый счёт",
    val thereAreNoCategories: String = "Категории отсутствуют, введите название новой категории",
    val thereAreNoAccounts: String = "Счета отсутствуют, введите название нового счёта",
    val selectIcon: String = "Выберите иконку",
    val search: String = "Поиск",
    val noIconsFound: String = "Иконки по этим критериям не найдены",
    val accountSettings: String = "Настройки счёта",
    val hideIfAmountIsZero: String = "Скрывать при нулевом балансе",
    val name: String = "Название",
    val settings: String = "Настройки",
    val categorySettings: String = "Настройки категории",
    val hue: String = "Цвет",
    val icon: String = "Иконка",
    val records: String = "Записи",
    val credits: String = "Доходы",
    val debits: String = "Расходы",
    val total: String = "Всего",
    val month: String = "месяц",
    val year: String = "год",
    val day: String = "день",
    val months: String = "месяцев",
    val years: String = "годов",
    val days: String = "дней",
    val inclusivePeriod: String = "Весь период",
    val fixedPeriod: String = "Выбранный период",
    val sum: String = "Сумма",
    val average: String = "Среднее",
    val sumFor: (period: String) -> String = { period -> "Сумма за $period" },
    val avgFor: (period: String, subperiod: String) -> String = { period, subperiod -> "Среднее в $subperiod за $period" },
    val synchronization: String = "Синхронизация",
    val synchronizationSettings: String = "Настройки синхронизации",
    val synchronizationSettingsNotExists: String = "Настройки синхронизации отсутствуют",
    val synchronizationSettingsNotSaved: String = "Настройки синхронизации не сохранены",
    val budgetConfig: String = "Настройки бюджета",
    val budgetConfigIsNotSaved: String = "Настройки бюджета не сохранены",
    val serverHost: String = "Адрес",
    val hostIsIncorrect: String = "Некорректный адрес",
    val httpScheme: String = "Протокол",
    val doConfig: String = "Настроить",
    val budgetConfigMain: String = "Основные",
    val budgetConfigSync: String = "Синхронизация",
    val nameShouldNotByEmpty: String = "Название не может быть пустым",
    val mantissaLength: String = "Количество знаков после запятой",
    val incorrectMantissaLength: String = "Некорректное количество знаков после запятой",
) {

    companion object {

        val default = Localization()
    }
}
