package org.hnau.pinfin.model.utils.budget.repository.demo

data class DemoBudgetConfig(
    val currencyRate: Double,
    val annualInflation: Double,
    val taxRate: Double,
    val localization: DemoBudgetLocalization,
)

data class DemoBudgetLocalization(
    val budgetTitle: String,
    val cardAccount: String,
    val savingsAccount: String,
    val salaryCategory: String,
    val bonusCategory: String,
    val taxCategory: String,
    val foodCategory: String,
    val homeCategory: String,
    val clothesCategory: String,
    val leisureCategory: String,
    val utilitiesCategory: String,
    val subscriptionsCategory: String,
    val healthCategory: String,
    val transportCategory: String,
    val rentCategory: String,
    val giftsCategory: String,
    val carCategory: String,
    val transferCategory: String,
    val cheapSupermarket: String,
    val midSupermarket: String,
    val expensiveSupermarket: String,
    val cheapClothingStore: String,
    val expensiveClothingStore: String,
    val homeStore: String,
    val cheapRestaurant: String,
    val expensiveRestaurant: String,
    val cinema: String,
    val theatre: String,
    val bar: String,
    val concertVenue: String,
    val pharmacy: String,
    val gasStation: String,
    val carService: String,
    val bread: String,
    val milk: String,
    val eggs: String,
    val cheese: String,
    val butter: String,
    val yogurt: String,
    val pasta: String,
    val rice: String,
    val tea: String,
    val coffee: String,
    val sugar: String,
    val oil: String,
    val chickenFillet: String,
    val sausages: String,
    val ketchup: String,
    val jam: String,
    val cookies: String,
    val chocolate: String,
    val chips: String,
    val soda: String,
    val juice: String,
    val potatoes: String,
    val apples: String,
    val tomatoes: String,
    val bananas: String,
    val oranges: String,
    val cabbage: String,
    val carrots: String,
    val onions: String,
    val meat: String,
    val fish: String,
    val cheeseByWeight: String,
    val sweetsBulk: String,
    val soap: String,
    val toothpaste: String,
    val shampoo: String,
    val detergent: String,
    val sponges: String,
    val toiletPaper: String,
    val lightBulbs: String,
    val trashBags: String,
    val pot: String,
    val plates: String,
    val cups: String,
    val towels: String,
    val lamp: String,
    val curtains: String,
    val chair: String,
    val bedLinen: String,
    val socks: String,
    val tshirt: String,
    val shirt: String,
    val jeans: String,
    val jacket: String,
    val sweater: String,
    val boots: String,
    val sneakers: String,
    val cinemaTicket: String,
    val theatreTicket: String,
    val concertTicket: String,
    val museumTicket: String,
    val bowling: String,
    val barBill: String,
    val painkillers: String,
    val vitamins: String,
    val bandAids: String,
    val coldMedicine: String,
    val doctorVisit: String,
    val dentistVisit: String,
    val busFare: String,
    val taxiRide: String,
    val gas: String,
    val carRepair: String,
    val carInsurance: String,
    val carWash: String,
    val streamingService: String,
    val gymMembership: String,
    val musicService: String,
    val cloudStorage: String,
    val electricity: String,
    val water: String,
    val heating: String,
    val internet: String,
    val phone: String,
    val wasteDisposal: String,
    val rent: String,
    val birthdayGift: String,
    val holidayGift: String,
    val salaryComment: String,
    val bonusComment: String,
    val taxComment: String,
    val transferToSavingsComment: String,
    val transferFromSavingsComment: String,
    val bigPurchaseComment: String,
    val giftComment: String,
) {
    companion object {

        val ru = DemoBudgetLocalization(
            budgetTitle = "Демо бюджет",
            cardAccount = "Карта",
            savingsAccount = "Накопительный",
            salaryCategory = "Зарплата",
            bonusCategory = "Премия",
            taxCategory = "Налог",
            foodCategory = "Еда",
            homeCategory = "Дом",
            clothesCategory = "Одежда",
            leisureCategory = "Досуг",
            utilitiesCategory = "ЖКХ",
            subscriptionsCategory = "Подписки",
            healthCategory = "Здоровье",
            transportCategory = "Транспорт",
            rentCategory = "Аренда",
            giftsCategory = "Подарки",
            carCategory = "Авто",
            transferCategory = "Перевод",
            cheapSupermarket = "Пятёрочка",
            midSupermarket = "Перекрёсток",
            expensiveSupermarket = "Азбука вкуса",
            cheapClothingStore = "Остин",
            expensiveClothingStore = "Zara",
            homeStore = "Леруа Мерлен",
            cheapRestaurant = "Макдоналдс",
            expensiveRestaurant = "Ресторан",
            cinema = "Кинотеатр",
            theatre = "Театр",
            bar = "Бар",
            concertVenue = "Концертный зал",
            pharmacy = "Аптека",
            gasStation = "АЗС",
            carService = "Автосервис",
            bread = "Хлеб",
            milk = "Молоко",
            eggs = "Яйца",
            cheese = "Сыр",
            butter = "Масло",
            yogurt = "Йогурт",
            pasta = "Макароны",
            rice = "Рис",
            tea = "Чай",
            coffee = "Кофе",
            sugar = "Сахар",
            oil = "Масло растительное",
            chickenFillet = "Куриное филе",
            sausages = "Сосиски",
            ketchup = "Кетчуп",
            jam = "Варенье",
            cookies = "Печенье",
            chocolate = "Шоколад",
            chips = "Чипсы",
            soda = "Газировка",
            juice = "Сок",
            potatoes = "Картофель",
            apples = "Яблоки",
            tomatoes = "Помидоры",
            bananas = "Бананы",
            oranges = "Апельсины",
            cabbage = "Капуста",
            carrots = "Морковь",
            onions = "Лук",
            meat = "Мясо",
            fish = "Рыба",
            cheeseByWeight = "Сыр весовой",
            sweetsBulk = "Сладости",
            soap = "Мыло",
            toothpaste = "Зубная паста",
            shampoo = "Шампунь",
            detergent = "Стиральный порошок",
            sponges = "Губки",
            toiletPaper = "Туалетная бумага",
            lightBulbs = "Лампочки",
            trashBags = "Мусорные пакеты",
            pot = "Кастрюля",
            plates = "Тарелки",
            cups = "Чашки",
            towels = "Полотенца",
            lamp = "Лампа",
            curtains = "Шторы",
            chair = "Стул",
            bedLinen = "Постельное бельё",
            socks = "Носки",
            tshirt = "Футболка",
            shirt = "Рубашка",
            jeans = "Джинсы",
            jacket = "Куртка",
            sweater = "Свитер",
            boots = "Ботинки",
            sneakers = "Кроссовки",
            cinemaTicket = "Билет в кино",
            theatreTicket = "Билет в театр",
            concertTicket = "Билет на концерт",
            museumTicket = "Билет в музей",
            bowling = "Боулинг",
            barBill = "Счёт в баре",
            painkillers = "Обезболивающее",
            vitamins = "Витамины",
            bandAids = "Пластыри",
            coldMedicine = "Лекарство от простуды",
            doctorVisit = "Приём врача",
            dentistVisit = "Стоматолог",
            busFare = "Проезд на автобусе",
            taxiRide = "Такси",
            gas = "Бензин",
            carRepair = "Ремонт авто",
            carInsurance = "Страховка авто",
            carWash = "Мойка авто",
            streamingService = "Стриминг",
            gymMembership = "Абонемент в зал",
            musicService = "Музыкальный сервис",
            cloudStorage = "Облачное хранилище",
            electricity = "Электричество",
            water = "Вода",
            heating = "Отопление",
            internet = "Интернет",
            phone = "Телефон",
            wasteDisposal = "Вывоз мусора",
            rent = "Аренда",
            birthdayGift = "Подарок на день рождения",
            holidayGift = "Подарок на праздник",
            salaryComment = "",
            bonusComment = "Годовая премия",
            taxComment = "Подоходный налог",
            transferToSavingsComment = "Остаток перед зарплатой",
            transferFromSavingsComment = "Не хватило на карте",
            bigPurchaseComment = "Крупная покупка",
            giftComment = "Подарок",
        )
    }
}
