//This file is generated

package hnau.pinfin.model.utils.icons

val IconVariant.title: String
    get() = variantTitle[ordinal]

private val variantTitle: List<String> = listOf(
    "Search",
    "Home",
    "Account circle",
    "Settings",
    "Done",
    "Info",
    "Close",
    "Check circle",
    "Delete",
    "Person",
    "Menu",
    "Expand more",
    "Add",
    "Visibility",
    "Shopping cart",
    "Edit",
    "Favorite",
    "Email",
    "Description",
    "Logout",
    "Arrow back",
    "Favorite border",
    "Chevron right",
    "Local shipping",
    "Lock",
    "Location on",
    "Schedule",
    "Notifications",
    "Call",
    "Language",
    "File download",
    "Arrow forward ios",
    "Arrow back ios",
    "Groups",
    "Cancel",
    "Help outline",
    "Arrow drop down",
    "Face",
    "Verified",
    "Manage accounts",
    "Play arrow",
    "Place",
    "More vert",
    "Add circle outline",
    "Thumb up",
    "Filter alt",
    "Event",
    "Dashboard",
    "Star",
    "Fingerprint",
    "List",
    "Content copy",
    "People",
    "Check circle outline",
    "Add circle",
    "Visibility off",
    "Login",
    "Send",
    "Arrow forward",
    "Chevron left",
    "Warning",
    "Calendar today",
    "Check box",
    "Share",
    "Highlight off",
    "Navigate next",
    "Help",
    "Phone",
    "Paid",
    "Task alt",
    "Question answer",
    "Expand less",
    "Error",
    "Check",
    "Clear",
    "Date range",
    "Article",
    "Photo camera",
    "Open in new",
    "Check box outline blank",
    "More horiz",
    "Image",
    "School",
    "Shopping bag",
    "Refresh",
    "Support agent",
    "Lightbulb",
    "Person outline",
    "Credit card",
    "File upload",
    "History",
    "Perm identity",
    "Trending up",
    "Account balance",
    "Delete outline",
    "Attach money",
    "Person add",
    "Save",
    "Public",
    "Verified user",
    "Radio button unchecked",
    "Error outline",
    "Fact check",
    "Assignment",
    "Mail",
    "Report problem",
    "Link",
    "Emoji events",
    "Star rate",
    "Play circle filled",
    "Remove",
    "Download",
    "Business",
    "Apps",
    "Calendar month",
    "Arrow right alt",
    "Filter list",
    "Chat",
    "Payments",
    "Menu book",
    "Folder",
    "Account balance wallet",
    "Autorenew",
    "Build",
    "View list",
    "Keyboard arrow down",
    "Tune",
    "Store",
    "Work",
    "Print",
    "Videocam",
    "Analytics",
    "Delete forever",
    "Radio button checked",
    "Phone iphone",
    "Play circle",
    "Mail outline",
    "Arrow upward",
    "Today",
    "Admin panel settings",
    "Grid view",
    "East",
    "Picture as pdf",
    "Mic",
    "Lock open",
    "Group",
    "Watch later",
    "Inventory 2",
    "Receipt long",
    "Volume up",
    "Grade",
    "Update",
    "Local offer",
    "Badge",
    "Inventory",
    "Circle",
    "Savings",
    "Room",
    "Edit note",
    "Code",
    "Map",
    "Light mode",
    "Add shopping cart",
    "Contact support",
    "Category",
    "Insights",
    "Receipt",
    "Power settings new",
    "Campaign",
    "Warning amber",
    "Format list bulleted",
    "Star border",
    "Restart alt",
    "Pause",
    "Done all",
    "Remove circle outline",
    "Pets",
    "Arrow back ios new",
    "Wifi",
    "List alt",
    "Storefront",
    "Engineering",
    "Mode edit",
    "Toggle on",
    "Notifications active",
    "Sort",
    "Bolt",
    "Dark mode",
    "Construction",
    "Qr code scanner",
    "Arrow downward",
    "Explore",
    "Attach file",
    "Bookmark",
    "Monetization on",
    "Vpn key",
    "Account box",
    "Note add",
    "Timer",
    "Reorder",
    "Pending actions",
    "Upload file",
    "Arrow right",
    "Bookmark border",
    "Account tree",
    "Smartphone",
    "Flag",
    "Apartment",
    "Shopping basket",
    "Sync",
    "Payment",
    "People alt",
    "Restaurant",
    "Play circle outline",
    "Reply",
    "Task",
    "Manage search",
    "Launch",
    "Add box",
    "Drag indicator",
    "Touch app",
    "Supervisor account",
    "Pending",
    "Menu open",
    "Zoom in",
    "Group add",
    "Push pin",
    "Priority high",
    "Auto awesome",
    "Remove circle",
    "Assessment",
    "Leaderboard",
    "Summarize",
    "Directions car",
    "Block",
    "Local fire department",
    "Thumb up off alt",
    "Chat bubble outline",
    "Event available",
    "Feed",
    "Open in full",
    "Auto stories",
    "Calculate",
    "Post add",
    "Cloud upload",
    "Alternate email",
    "Bar chart",
    "Done outline",
    "Password",
    "Preview",
    "Assignment ind",
    "Collections",
    "Published with changes",
    "Create",
    "Psychology",
    "Exit to app",
    "Checklist",
    "Volunteer activism",
    "Star outline",
    "Card giftcard",
    "Navigate before",
    "Undo",
    "Sell",
    "Thumb up alt",
    "Add a photo",
    "View in ar",
    "Fullscreen",
    "Tips and updates",
    "Health and safety",
    "Feedback",
    "Arrow drop up",
    "Label",
    "Travel explore",
    "Unfold more",
    "Water drop",
    "Swap horiz",
    "Computer",
    "Palette",
    "Keyboard arrow right",
    "Timeline",
    "Stars",
    "Assignment turned in",
    "Sync alt",
    "Dns",
    "Replay",
    "Work outline",
    "Double arrow",
    "Signal cellular alt",
    "Notifications none",
    "Flight takeoff",
    "Volume off",
    "Skip next",
    "How to reg",
    "Library books",
    "Forum",
    "Emoji emotions",
    "Devices",
    "Chat bubble",
    "Folder open",
    "Maps home work",
    "Fiber manual record",
    "Content paste",
    "Cloud",
    "Security",
    "Text snippet",
    "Remove red eye",
    "My location",
    "Sports esports",
    "Request quote",
    "Textsms",
    "Alarm",
    "Settings suggest",
    "Space dashboard",
    "Toggle off",
    "Speed",
    "Workspace premium",
    "Sentiment very satisfied",
    "Contact page",
    "Cached",
    "Report",
    "Bug report",
    "Book",
    "Translate",
    "Stop",
    "Gavel",
    "Rocket launch",
    "Quiz",
    "Edit calendar",
    "Pan tool",
    "Cloud download",
    "Question mark",
    "File copy",
    "Person search",
    "Contact mail",
    "Sentiment satisfied alt",
    "Supervised user circle",
    "Minimize",
    "Qr code",
    "Location city",
    "Widgets",
    "Desktop windows",
    "Extension",
    "Ios share",
    "Flight",
    "Precision manufacturing",
    "Qr code 2",
    "Local mall",
    "Music note",
    "Fitness center",
    "Backspace",
    "Android",
    "Smart display",
    "Near me",
    "Drag handle",
    "Record voice over",
    "Get app",
    "Accessibility",
    "Add task",
    "Shield",
    "West",
    "Message",
    "Hourglass empty",
    "Show chart",
    "Storage",
    "Sentiment satisfied",
    "Insert drive file",
    "Science",
    "Handyman",
    "Drive file rename outline",
    "Help center",
    "Person add alt",
    "Military tech",
    "Trending flat",
    "Directions run",
    "Rule",
    "Movie",
    "Emoji objects",
    "Accessibility new",
    "Thumb down",
    "Confirmation number",
    "Event note",
    "Contacts",
    "Format quote",
    "Comment",
    "Ads click",
    "Swap vert",
    "Restaurant menu",
    "Add photo alternate",
    "History edu",
    "Skip previous",
    "Archive",
    "Settings applications",
    "Business center",
    "Upload",
    "Sticky note 2",
    "Source",
    "Find in page",
    "Credit score",
    "Cake",
    "Query stats",
    "Dashboard customize",
    "New releases",
    "Save alt",
    "Playlist add",
    "Redeem",
    "Support",
    "Arrow circle right",
    "Loyalty",
    "Attachment",
    "Wb sunny",
    "Announcement",
    "Spa",
    "Thermostat",
    "Close fullscreen",
    "Flutter dash",
    "Layers",
    "Key",
    "Format list numbered",
    "Restore",
    "Handshake",
    "Expand circle down",
    "View headline",
    "Keyboard backspace",
    "Medical services",
    "Currency exchange",
    "Policy",
    "Phone android",
    "Dangerous",
    "Sms",
    "Sentiment dissatisfied",
    "Directions walk",
    "Euro symbol",
    "Keyboard arrow up",
    "Table chart",
    "Sensors",
    "Meeting room",
    "Keyboard return",
    "Border color",
    "Group work",
    "Sentiment very dissatisfied",
    "Brush",
    "Battery full",
    "Gps fixed",
    "Keyboard double arrow right",
    "Table view",
    "Compare arrows",
    "Notification important",
    "House",
    "Change circle",
    "Disabled by default",
    "Arrow left",
    "South",
    "Local hospital",
    "Celebration",
    "Tag",
    "Subject",
    "Lunch dining",
    "Import contacts",
    "Loop",
    "Laptop",
    "Privacy tip",
    "Smart toy",
    "App registration",
    "Equalizer",
    "Price check",
    "Local library",
    "Euro",
    "Nightlight round",
    "Corporate fare",
    "Flash on",
    "Pin drop",
    "Ac unit",
    "Live tv",
    "Bookmarks",
    "Https",
    "Toc",
    "Arrow circle up",
    "Track changes",
    "Contact phone",
    "Input",
    "Park",
    "Newspaper",
    "View module",
    "Keyboard arrow left",
    "Medication",
    "Emoji people",
    "Api",
    "Pie chart",
    "Import export",
    "Auto fix high",
    "Self improvement",
    "Download for offline",
    "Grading",
    "Query builder",
    "Perm media",
    "Copyright",
    "Live help",
    "Pin",
    "Fast forward",
    "Forward to inbox",
    "Person remove",
    "Coronavirus",
    "Local atm",
    "Looks one",
    "Build circle",
    "North east",
    "Redo",
    "Hourglass bottom",
    "Web",
    "Local activity",
    "Memory",
    "Forward",
)