//This file is generated

package hnau.pinfin.model.utils.icons

val IconVariant.category: IconCategory
    get() = variantCategory[ordinal]

private val variantCategory: List<IconCategory> = buildList {
    addAll(getCategory0())
    addAll(getCategory1())
    addAll(getCategory2())
    addAll(getCategory3())
    addAll(getCategory4())
    addAll(getCategory5())
    addAll(getCategory6())
    addAll(getCategory7())
    addAll(getCategory8())
    addAll(getCategory9())
    addAll(getCategory10())
    addAll(getCategory11())
    addAll(getCategory12())
    addAll(getCategory13())
    addAll(getCategory14())
    addAll(getCategory15())
    addAll(getCategory16())
    addAll(getCategory17())
    addAll(getCategory18())
    addAll(getCategory19())
    addAll(getCategory20())
    addAll(getCategory21())
    addAll(getCategory22())
    addAll(getCategory23())
    addAll(getCategory24())
    addAll(getCategory25())
    addAll(getCategory26())
    addAll(getCategory27())
    addAll(getCategory28())
    addAll(getCategory29())
    addAll(getCategory30())
    addAll(getCategory31())
    addAll(getCategory32())
    addAll(getCategory33())
    addAll(getCategory34())
    addAll(getCategory35())
    addAll(getCategory36())
    addAll(getCategory37())
    addAll(getCategory38())
    addAll(getCategory39())
    addAll(getCategory40())
    addAll(getCategory41())
    addAll(getCategory42())
}

private fun getCategory0(): List<IconCategory> = listOf(
    IconCategory.Action, //Search
    IconCategory.Action, //Home
    IconCategory.Action, //AccountCircle
    IconCategory.Action, //Settings
    IconCategory.Action, //Done
    IconCategory.Action, //Info
    IconCategory.Navigation, //Close
    IconCategory.Action, //CheckCircle
    IconCategory.Action, //Delete
    IconCategory.Social, //Person
    IconCategory.Navigation, //Menu
    IconCategory.Navigation, //ExpandMore
    IconCategory.Content, //Add
    IconCategory.Action, //Visibility
    IconCategory.Action, //ShoppingCart
    IconCategory.Image, //Edit
    IconCategory.Action, //Favorite
    IconCategory.Communication, //Email
    IconCategory.Action, //Description
    IconCategory.Action, //Logout
    IconCategory.Navigation, //ArrowBack
    IconCategory.Action, //FavoriteBorder
    IconCategory.Navigation, //ChevronRight
    IconCategory.Maps, //LocalShipping
    IconCategory.Action, //Lock
    IconCategory.Communication, //LocationOn
    IconCategory.Action, //Schedule
    IconCategory.Social, //Notifications
    IconCategory.Communication, //Call
    IconCategory.Action, //Language
    IconCategory.File, //FileDownload
    IconCategory.Navigation, //ArrowForwardIos
    IconCategory.Navigation, //ArrowBackIos
    IconCategory.Social, //Groups
    IconCategory.Navigation, //Cancel
    IconCategory.Action, //HelpOutline
    IconCategory.Navigation, //ArrowDropDown
    IconCategory.Action, //Face
    IconCategory.Action, //Verified
    IconCategory.Action, //ManageAccounts
    IconCategory.Av, //PlayArrow
    IconCategory.Maps, //Place
    IconCategory.Navigation, //MoreVert
    IconCategory.Content, //AddCircleOutline
    IconCategory.Action, //ThumbUp
    IconCategory.Action, //FilterAlt
    IconCategory.Action, //Event
    IconCategory.Action, //Dashboard
    IconCategory.Toggle, //Star
    IconCategory.Action, //Fingerprint
)

private fun getCategory1(): List<IconCategory> = listOf(
    IconCategory.Action, //List
    IconCategory.Content, //ContentCopy
    IconCategory.Social, //People
    IconCategory.Action, //CheckCircleOutline
    IconCategory.Content, //AddCircle
    IconCategory.Action, //VisibilityOff
    IconCategory.Action, //Login
    IconCategory.Content, //Send
    IconCategory.Navigation, //ArrowForward
    IconCategory.Navigation, //ChevronLeft
    IconCategory.Alert, //Warning
    IconCategory.Action, //CalendarToday
    IconCategory.Toggle, //CheckBox
    IconCategory.Social, //Share
    IconCategory.Action, //HighlightOff
    IconCategory.Image, //NavigateNext
    IconCategory.Action, //Help
    IconCategory.Communication, //Phone
    IconCategory.Action, //Paid
    IconCategory.Action, //TaskAlt
    IconCategory.Action, //QuestionAnswer
    IconCategory.Navigation, //ExpandLess
    IconCategory.Alert, //Error
    IconCategory.Navigation, //Check
    IconCategory.Content, //Clear
    IconCategory.Action, //DateRange
    IconCategory.Action, //Article
    IconCategory.Image, //PhotoCamera
    IconCategory.Action, //OpenInNew
    IconCategory.Toggle, //CheckBoxOutlineBlank
    IconCategory.Navigation, //MoreHoriz
    IconCategory.Image, //Image
    IconCategory.Social, //School
    IconCategory.Action, //ShoppingBag
    IconCategory.Navigation, //Refresh
    IconCategory.Notification, //SupportAgent
    IconCategory.Action, //Lightbulb
    IconCategory.Social, //PersonOutline
    IconCategory.Action, //CreditCard
    IconCategory.File, //FileUpload
    IconCategory.Action, //History
    IconCategory.Action, //PermIdentity
    IconCategory.Action, //TrendingUp
    IconCategory.Action, //AccountBalance
    IconCategory.Action, //DeleteOutline
    IconCategory.Editor, //AttachMoney
    IconCategory.Social, //PersonAdd
    IconCategory.Content, //Save
    IconCategory.Social, //Public
    IconCategory.Action, //VerifiedUser
)

private fun getCategory2(): List<IconCategory> = listOf(
    IconCategory.Toggle, //RadioButtonUnchecked
    IconCategory.Alert, //ErrorOutline
    IconCategory.Action, //FactCheck
    IconCategory.Action, //Assignment
    IconCategory.Content, //Mail
    IconCategory.Action, //ReportProblem
    IconCategory.Content, //Link
    IconCategory.Social, //EmojiEvents
    IconCategory.Action, //StarRate
    IconCategory.Av, //PlayCircleFilled
    IconCategory.Content, //Remove
    IconCategory.File, //Download
    IconCategory.Communication, //Business
    IconCategory.Navigation, //Apps
    IconCategory.Action, //CalendarMonth
    IconCategory.Action, //ArrowRightAlt
    IconCategory.Content, //FilterList
    IconCategory.Communication, //Chat
    IconCategory.Navigation, //Payments
    IconCategory.Maps, //MenuBook
    IconCategory.File, //Folder
    IconCategory.Action, //AccountBalanceWallet
    IconCategory.Action, //Autorenew
    IconCategory.Action, //Build
    IconCategory.Action, //ViewList
    IconCategory.Hardware, //KeyboardArrowDown
    IconCategory.Image, //Tune
    IconCategory.Action, //Store
    IconCategory.Action, //Work
    IconCategory.Action, //Print
    IconCategory.Av, //Videocam
    IconCategory.Action, //Analytics
    IconCategory.Action, //DeleteForever
    IconCategory.Toggle, //RadioButtonChecked
    IconCategory.Hardware, //PhoneIphone
    IconCategory.Av, //PlayCircle
    IconCategory.Communication, //MailOutline
    IconCategory.Navigation, //ArrowUpward
    IconCategory.Action, //Today
    IconCategory.Action, //AdminPanelSettings
    IconCategory.File, //GridView
    IconCategory.Navigation, //East
    IconCategory.Image, //PictureAsPdf
    IconCategory.Av, //Mic
    IconCategory.Action, //LockOpen
    IconCategory.Social, //Group
    IconCategory.Action, //WatchLater
    IconCategory.Content, //Inventory2
    IconCategory.Image, //ReceiptLong
    IconCategory.Av, //VolumeUp
)

private fun getCategory3(): List<IconCategory> = listOf(
    IconCategory.Action, //Grade
    IconCategory.Action, //Update
    IconCategory.Maps, //LocalOffer
    IconCategory.Maps, //Badge
    IconCategory.Content, //Inventory
    IconCategory.Image, //Circle
    IconCategory.Action, //Savings
    IconCategory.Action, //Room
    IconCategory.Editor, //EditNote
    IconCategory.Action, //Code
    IconCategory.Maps, //Map
    IconCategory.Device, //LightMode
    IconCategory.Action, //AddShoppingCart
    IconCategory.Action, //ContactSupport
    IconCategory.Maps, //Category
    IconCategory.Content, //Insights
    IconCategory.Action, //Receipt
    IconCategory.Action, //PowerSettingsNew
    IconCategory.Navigation, //Campaign
    IconCategory.Alert, //WarningAmber
    IconCategory.Editor, //FormatListBulleted
    IconCategory.Toggle, //StarBorder
    IconCategory.Device, //RestartAlt
    IconCategory.Av, //Pause
    IconCategory.Action, //DoneAll
    IconCategory.Content, //RemoveCircleOutline
    IconCategory.Action, //Pets
    IconCategory.Navigation, //ArrowBackIosNew
    IconCategory.Notification, //Wifi
    IconCategory.Communication, //ListAlt
    IconCategory.Places, //Storefront
    IconCategory.Social, //Engineering
    IconCategory.Editor, //ModeEdit
    IconCategory.Toggle, //ToggleOn
    IconCategory.Social, //NotificationsActive
    IconCategory.Content, //Sort
    IconCategory.Content, //Bolt
    IconCategory.Device, //DarkMode
    IconCategory.Social, //Construction
    IconCategory.Communication, //QrCodeScanner
    IconCategory.Navigation, //ArrowDownward
    IconCategory.Action, //Explore
    IconCategory.Editor, //AttachFile
    IconCategory.Action, //Bookmark
    IconCategory.Editor, //MonetizationOn
    IconCategory.Communication, //VpnKey
    IconCategory.Action, //AccountBox
    IconCategory.Action, //NoteAdd
    IconCategory.Image, //Timer
    IconCategory.Action, //Reorder
)

private fun getCategory4(): List<IconCategory> = listOf(
    IconCategory.Action, //PendingActions
    IconCategory.File, //UploadFile
    IconCategory.Navigation, //ArrowRight
    IconCategory.Action, //BookmarkBorder
    IconCategory.Notification, //AccountTree
    IconCategory.Hardware, //Smartphone
    IconCategory.Content, //Flag
    IconCategory.Places, //Apartment
    IconCategory.Action, //ShoppingBasket
    IconCategory.Notification, //Sync
    IconCategory.Action, //Payment
    IconCategory.Social, //PeopleAlt
    IconCategory.Maps, //Restaurant
    IconCategory.Av, //PlayCircleOutline
    IconCategory.Content, //Reply
    IconCategory.Device, //Task
    IconCategory.Search, //ManageSearch
    IconCategory.Action, //Launch
    IconCategory.Content, //AddBox
    IconCategory.Action, //DragIndicator
    IconCategory.Action, //TouchApp
    IconCategory.Action, //SupervisorAccount
    IconCategory.Action, //Pending
    IconCategory.Navigation, //MenuOpen
    IconCategory.Action, //ZoomIn
    IconCategory.Social, //GroupAdd
    IconCategory.Image, //AutoAwesome
    IconCategory.Notification, //PriorityHigh
    IconCategory.Content, //PushPin
    IconCategory.Content, //RemoveCircle
    IconCategory.Action, //Assessment
    IconCategory.Action, //Leaderboard
    IconCategory.Device, //Summarize
    IconCategory.Maps, //DirectionsCar
    IconCategory.Content, //Block
    IconCategory.Maps, //LocalFireDepartment
    IconCategory.Action, //ThumbUpOffAlt
    IconCategory.Communication, //ChatBubbleOutline
    IconCategory.Notification, //EventAvailable
    IconCategory.Search, //Feed
    IconCategory.Action, //OpenInFull
    IconCategory.Image, //AutoStories
    IconCategory.Content, //Calculate
    IconCategory.Editor, //PostAdd
    IconCategory.File, //CloudUpload
    IconCategory.Communication, //AlternateEmail
    IconCategory.Editor, //BarChart
    IconCategory.Action, //DoneOutline
    IconCategory.Device, //Password
    IconCategory.Action, //Preview
)

private fun getCategory5(): List<IconCategory> = listOf(
    IconCategory.Action, //AssignmentInd
    IconCategory.Image, //Collections
    IconCategory.Action, //PublishedWithChanges
    IconCategory.Content, //Create
    IconCategory.Social, //Psychology
    IconCategory.Action, //ExitToApp
    IconCategory.Editor, //Checklist
    IconCategory.Maps, //VolunteerActivism
    IconCategory.Toggle, //StarOutline
    IconCategory.Action, //CardGiftcard
    IconCategory.Image, //NavigateBefore
    IconCategory.Content, //Undo
    IconCategory.Device, //Sell
    IconCategory.Social, //ThumbUpAlt
    IconCategory.Image, //AddAPhoto
    IconCategory.Action, //ViewInAr
    IconCategory.Navigation, //Fullscreen
    IconCategory.Action, //TipsAndUpdates
    IconCategory.Social, //HealthAndSafety
    IconCategory.Action, //Feedback
    IconCategory.Navigation, //ArrowDropUp
    IconCategory.Action, //Label
    IconCategory.Social, //TravelExplore
    IconCategory.Navigation, //UnfoldMore
    IconCategory.Social, //WaterDrop
    IconCategory.Action, //SwapHoriz
    IconCategory.Hardware, //Computer
    IconCategory.Image, //Palette
    IconCategory.Hardware, //KeyboardArrowRight
    IconCategory.Action, //Timeline
    IconCategory.Action, //Stars
    IconCategory.Action, //AssignmentTurnedIn
    IconCategory.Action, //SyncAlt
    IconCategory.Action, //Dns
    IconCategory.Av, //Replay
    IconCategory.Action, //WorkOutline
    IconCategory.Navigation, //DoubleArrow
    IconCategory.Device, //SignalCellularAlt
    IconCategory.Social, //NotificationsNone
    IconCategory.Action, //FlightTakeoff
    IconCategory.Av, //VolumeOff
    IconCategory.Av, //SkipNext
    IconCategory.Content, //HowToReg
    IconCategory.Av, //LibraryBooks
    IconCategory.Communication, //Forum
    IconCategory.Social, //EmojiEmotions
    IconCategory.Device, //Devices
    IconCategory.Communication, //ChatBubble
    IconCategory.File, //FolderOpen
    IconCategory.Navigation, //MapsHomeWork
)

private fun getCategory6(): List<IconCategory> = listOf(
    IconCategory.Av, //FiberManualRecord
    IconCategory.Content, //ContentPaste
    IconCategory.File, //Cloud
    IconCategory.Hardware, //Security
    IconCategory.File, //TextSnippet
    IconCategory.Image, //RemoveRedEye
    IconCategory.Maps, //MyLocation
    IconCategory.Social, //SportsEsports
    IconCategory.File, //RequestQuote
    IconCategory.Communication, //Textsms
    IconCategory.Action, //Alarm
    IconCategory.Device, //SettingsSuggest
    IconCategory.Action, //SpaceDashboard
    IconCategory.Toggle, //ToggleOff
    IconCategory.Av, //Speed
    IconCategory.Social, //WorkspacePremium
    IconCategory.Social, //SentimentVerySatisfied
    IconCategory.Action, //ContactPage
    IconCategory.Action, //Cached
    IconCategory.Content, //Report
    IconCategory.Action, //BugReport
    IconCategory.Action, //Book
    IconCategory.Action, //Translate
    IconCategory.Av, //Stop
    IconCategory.Action, //Gavel
    IconCategory.Action, //RocketLaunch
    IconCategory.Device, //Quiz
    IconCategory.Action, //PanTool
    IconCategory.Action, //EditCalendar
    IconCategory.Action, //QuestionMark
    IconCategory.File, //CloudDownload
    IconCategory.Content, //FileCopy
    IconCategory.Communication, //PersonSearch
    IconCategory.Communication, //ContactMail
    IconCategory.Communication, //SentimentSatisfiedAlt
    IconCategory.Action, //SupervisedUserCircle
    IconCategory.Action, //Minimize
    IconCategory.Communication, //QrCode
    IconCategory.Social, //LocationCity
    IconCategory.Device, //Widgets
    IconCategory.Hardware, //DesktopWindows
    IconCategory.Action, //Extension
    IconCategory.Social, //IosShare
    IconCategory.Maps, //Flight
    IconCategory.Social, //PrecisionManufacturing
    IconCategory.Communication, //QrCode2
    IconCategory.Maps, //LocalMall
    IconCategory.Image, //MusicNote
    IconCategory.Places, //FitnessCenter
    IconCategory.Content, //Backspace
)

private fun getCategory7(): List<IconCategory> = listOf(
    IconCategory.Action, //Android
    IconCategory.Hardware, //SmartDisplay
    IconCategory.Maps, //NearMe
    IconCategory.Editor, //DragHandle
    IconCategory.Action, //RecordVoiceOver
    IconCategory.Action, //GetApp
    IconCategory.Action, //Accessibility
    IconCategory.Action, //AddTask
    IconCategory.Content, //Shield
    IconCategory.Navigation, //West
    IconCategory.Communication, //Message
    IconCategory.Action, //HourglassEmpty
    IconCategory.Editor, //ShowChart
    IconCategory.Device, //Storage
    IconCategory.Social, //SentimentSatisfied
    IconCategory.Editor, //InsertDriveFile
    IconCategory.Social, //Science
    IconCategory.Maps, //Handyman
    IconCategory.File, //DriveFileRenameOutline
    IconCategory.Action, //HelpCenter
    IconCategory.Social, //PersonAddAlt
    IconCategory.Social, //MilitaryTech
    IconCategory.Action, //TrendingFlat
    IconCategory.Maps, //DirectionsRun
    IconCategory.Action, //Rule
    IconCategory.Av, //Movie
    IconCategory.Social, //EmojiObjects
    IconCategory.Action, //AccessibilityNew
    IconCategory.Action, //ThumbDown
    IconCategory.Notification, //ConfirmationNumber
    IconCategory.Notification, //EventNote
    IconCategory.Communication, //Contacts
    IconCategory.Editor, //FormatQuote
    IconCategory.Communication, //Comment
    IconCategory.Action, //AdsClick
    IconCategory.Action, //SwapVert
    IconCategory.Maps, //RestaurantMenu
    IconCategory.Image, //AddPhotoAlternate
    IconCategory.Social, //HistoryEdu
    IconCategory.Av, //SkipPrevious
    IconCategory.Content, //Archive
    IconCategory.Action, //SettingsApplications
    IconCategory.Places, //BusinessCenter
    IconCategory.File, //Upload
    IconCategory.Action, //StickyNote2
    IconCategory.Action, //Source
    IconCategory.Action, //FindInPage
    IconCategory.Device, //CreditScore
    IconCategory.Social, //Cake
    IconCategory.Editor, //QueryStats
)

private fun getCategory8(): List<IconCategory> = listOf(
    IconCategory.Action, //DashboardCustomize
    IconCategory.Av, //NewReleases
    IconCategory.Content, //SaveAlt
    IconCategory.Av, //PlaylistAdd
    IconCategory.Action, //Redeem
    IconCategory.Action, //Support
    IconCategory.Action, //ArrowCircleRight
    IconCategory.Action, //Loyalty
    IconCategory.File, //Attachment
    IconCategory.Image, //WbSunny
    IconCategory.Action, //Announcement
    IconCategory.Places, //Spa
    IconCategory.Device, //Thermostat
    IconCategory.Action, //CloseFullscreen
    IconCategory.Action, //FlutterDash
    IconCategory.Maps, //Layers
    IconCategory.Communication, //Key
    IconCategory.Editor, //FormatListNumbered
    IconCategory.Action, //Restore
    IconCategory.Social, //Handshake
    IconCategory.Navigation, //ExpandCircleDown
    IconCategory.Action, //ViewHeadline
    IconCategory.Hardware, //KeyboardBackspace
    IconCategory.Maps, //MedicalServices
    IconCategory.Action, //CurrencyExchange
    IconCategory.Content, //Policy
    IconCategory.Hardware, //PhoneAndroid
    IconCategory.Action, //Dangerous
    IconCategory.Notification, //Sms
    IconCategory.Social, //SentimentDissatisfied
    IconCategory.Maps, //DirectionsWalk
    IconCategory.Action, //EuroSymbol
    IconCategory.Hardware, //KeyboardArrowUp
    IconCategory.Editor, //TableChart
    IconCategory.Action, //Sensors
    IconCategory.Places, //MeetingRoom
    IconCategory.Hardware, //KeyboardReturn
    IconCategory.Editor, //BorderColor
    IconCategory.Action, //GroupWork
    IconCategory.Social, //SentimentVeryDissatisfied
    IconCategory.Image, //Brush
    IconCategory.Device, //BatteryFull
    IconCategory.Device, //GpsFixed
    IconCategory.Hardware, //KeyboardDoubleArrowRight
    IconCategory.Action, //TableView
    IconCategory.Action, //CompareArrows
    IconCategory.Alert, //NotificationImportant
    IconCategory.Places, //House
    IconCategory.Content, //ChangeCircle
    IconCategory.Action, //DisabledByDefault
)

private fun getCategory9(): List<IconCategory> = listOf(
    IconCategory.Navigation, //ArrowLeft
    IconCategory.Navigation, //South
    IconCategory.Maps, //LocalHospital
    IconCategory.Maps, //Celebration
    IconCategory.Content, //Tag
    IconCategory.Action, //Subject
    IconCategory.Maps, //LunchDining
    IconCategory.Communication, //ImportContacts
    IconCategory.Av, //Loop
    IconCategory.Hardware, //Laptop
    IconCategory.Action, //PrivacyTip
    IconCategory.Hardware, //SmartToy
    IconCategory.Communication, //AppRegistration
    IconCategory.Av, //Equalizer
    IconCategory.Device, //PriceCheck
    IconCategory.Maps, //LocalLibrary
    IconCategory.Image, //Euro
    IconCategory.Action, //NightlightRound
    IconCategory.Places, //CorporateFare
    IconCategory.Image, //FlashOn
    IconCategory.Maps, //PinDrop
    IconCategory.Places, //AcUnit
    IconCategory.Notification, //LiveTv
    IconCategory.Action, //Bookmarks
    IconCategory.Action, //Https
    IconCategory.Action, //Toc
    IconCategory.Action, //ArrowCircleUp
    IconCategory.Action, //TrackChanges
    IconCategory.Communication, //ContactPhone
    IconCategory.Action, //Input
    IconCategory.Maps, //Park
    IconCategory.File, //Newspaper
    IconCategory.Action, //ViewModule
    IconCategory.Hardware, //KeyboardArrowLeft
    IconCategory.Social, //EmojiPeople
    IconCategory.Action, //Api
    IconCategory.Device, //Medication
    IconCategory.Editor, //PieChart
    IconCategory.Communication, //ImportExport
    IconCategory.Image, //AutoFixHigh
    IconCategory.Social, //SelfImprovement
    IconCategory.File, //DownloadForOffline
    IconCategory.Action, //Grading
    IconCategory.Action, //QueryBuilder
    IconCategory.Action, //PermMedia
    IconCategory.Action, //Copyright
    IconCategory.Communication, //LiveHelp
    IconCategory.Device, //Pin
    IconCategory.Av, //FastForward
    IconCategory.Communication, //ForwardToInbox
)

private fun getCategory10(): List<IconCategory> = listOf(
    IconCategory.Social, //PersonRemove
    IconCategory.Social, //Coronavirus
    IconCategory.Maps, //LocalAtm
    IconCategory.Image, //LooksOne
    IconCategory.Action, //BuildCircle
    IconCategory.Navigation, //NorthEast
    IconCategory.Content, //Redo
    IconCategory.Communication, //HourglassBottom
    IconCategory.Av, //Web
    IconCategory.Maps, //LocalActivity
    IconCategory.Hardware, //Memory
    IconCategory.Content, //Forward
    IconCategory.Navigation, //North
    IconCategory.Toggle, //StarHalf
    IconCategory.Av, //PlaylistAddCheck
    IconCategory.Action, //PermContactCalendar
    IconCategory.Maps, //PersonPin
    IconCategory.Av, //VideoLibrary
    IconCategory.Maps, //DesignServices
    IconCategory.Maps, //DirectionsBus
    IconCategory.Action, //ZoomOut
    IconCategory.Device, //GppGood
    IconCategory.Communication, //HourglassTop
    IconCategory.Action, //SettingsPhone
    IconCategory.Hardware, //Headphones
    IconCategory.Social, //Poll
    IconCategory.Action, //Backup
    IconCategory.Navigation, //FirstPage
    IconCategory.Action, //OpenWith
    IconCategory.Places, //Cottage
    IconCategory.Maps, //LocalCafe
    IconCategory.Content, //ContentCut
    IconCategory.Notification, //OndemandVideo
    IconCategory.Hardware, //PointOfSale
    IconCategory.Navigation, //HomeWork
    IconCategory.Maps, //RateReview
    IconCategory.Hardware, //Keyboard
    IconCategory.Action, //CircleNotifications
    IconCategory.Communication, //RssFeed
    IconCategory.Maps, //DeliveryDining
    IconCategory.Social, //Whatshot
    IconCategory.Image, //ControlPoint
    IconCategory.Action, //PermPhoneMsg
    IconCategory.Hardware, //HeadsetMic
    IconCategory.Editor, //Notes
    IconCategory.Action, //SpeakerNotes
    IconCategory.Action, //LabelImportant
    IconCategory.Image, //Style
    IconCategory.Action, //Wysiwyg
    IconCategory.File, //CreateNewFolder
)

private fun getCategory11(): List<IconCategory> = listOf(
    IconCategory.Action, //CardMembership
    IconCategory.Toggle, //IndeterminateCheckBox
    IconCategory.Device, //BatteryChargingFull
    IconCategory.Content, //OutlinedFlag
    IconCategory.Social, //SportsSoccer
    IconCategory.Action, //BookOnline
    IconCategory.Navigation, //FullscreenExit
    IconCategory.Action, //FilePresent
    IconCategory.Communication, //MarkEmailRead
    IconCategory.Action, //ArrowCircleDown
    IconCategory.Device, //PriceChange
    IconCategory.Image, //Adjust
    IconCategory.Av, //LibraryAdd
    IconCategory.Action, //Pageview
    IconCategory.Social, //Domain
    IconCategory.Maps, //LocalPolice
    IconCategory.Hardware, //Tv
    IconCategory.Content, //Inbox
    IconCategory.Action, //Percent
    IconCategory.Social, //Recommend
    IconCategory.Image, //Straighten
    IconCategory.Av, //PauseCircle
    IconCategory.Search, //Chair
    IconCategory.Device, //Reviews
    IconCategory.Notification, //DriveEta
    IconCategory.Device, //FmdGood
    IconCategory.Social, //Mood
    IconCategory.Maps, //DirectionsBike
    IconCategory.Av, //MicOff
    IconCategory.Maps, //Fastfood
    IconCategory.Action, //Upgrade
    IconCategory.Action, //TrendingDown
    IconCategory.Action, //ChangeHistory
    IconCategory.Content, //LinkOff
    IconCategory.Av, //StopCircle
    IconCategory.Action, //IntegrationInstructions
    IconCategory.Social, //PeopleOutline
    IconCategory.Action, //_3dRotation
    IconCategory.Device, //Tungsten
    IconCategory.Editor, //ChecklistRtl
    IconCategory.Maps, //DirectionsCarFilled
    IconCategory.Maps, //HomeRepairService
    IconCategory.Editor, //TextFields
    IconCategory.Editor, //FormatBold
    IconCategory.Social, //Recycling
    IconCategory.Av, //Subscriptions
    IconCategory.Maps, //CleaningServices
    IconCategory.Maps, //ZoomOutMap
    IconCategory.Editor, //TableRows
    IconCategory.Search, //Bed
)

private fun getCategory12(): List<IconCategory> = listOf(
    IconCategory.Editor, //Publish
    IconCategory.Notification, //WifiOff
    IconCategory.Av, //Repeat
    IconCategory.Content, //Ballot
    IconCategory.Social, //Female
    IconCategory.Av, //VolumeMute
    IconCategory.Action, //Accessible
    IconCategory.Content, //Drafts
    IconCategory.Places, //FamilyRestroom
    IconCategory.Content, //Biotech
    IconCategory.Action, //Class
    IconCategory.Av, //VideoCall
    IconCategory.Action, //Swipe
    IconCategory.Navigation, //LastPage
    IconCategory.Maps, //Hotel
    IconCategory.Editor, //Title
    IconCategory.Action, //GTranslate
    IconCategory.Navigation, //ArrowDropDownCircle
    IconCategory.Device, //Air
    IconCategory.Action, //SettingsAccessibility
    IconCategory.Communication, //Hub
    IconCategory.Action, //ArrowCircleLeft
    IconCategory.Social, //PersonOff
    IconCategory.Editor, //InsertEmoticon
    IconCategory.Action, //SettingsBackupRestore
    IconCategory.Action, //OfflineBolt
    IconCategory.Editor, //AutoGraph
    IconCategory.File, //Downloading
    IconCategory.Action, //ProductionQuantityLimits
    IconCategory.Action, //Expand
    IconCategory.Image, //PhotoLibrary
    IconCategory.Content, //ReportGmailerrorred
    IconCategory.Av, //NotInterested
    IconCategory.Device, //NoteAlt
    IconCategory.Maps, //MiscellaneousServices
    IconCategory.Notification, //EventBusy
    IconCategory.Maps, //LocalPhone
    IconCategory.Maps, //LocalGroceryStore
    IconCategory.Hardware, //KeyboardDoubleArrowLeft
    IconCategory.Editor, //InsertPhoto
    IconCategory.Image, //Camera
    IconCategory.Editor, //Draw
    IconCategory.Editor, //InsertChartOutlined
    IconCategory.Action, //ViewColumn
    IconCategory.Action, //AspectRatio
    IconCategory.Navigation, //UnfoldLess
    IconCategory.Places, //Checkroom
    IconCategory.Av, //Shuffle
    IconCategory.Action, //ModelTraining
    IconCategory.Action, //DonutLarge
)

private fun getCategory13(): List<IconCategory> = listOf(
    IconCategory.Social, //Male
    IconCategory.Action, //Segment
    IconCategory.Image, //Portrait
    IconCategory.Content, //DeleteSweep
    IconCategory.Places, //OtherHouses
    IconCategory.Device, //Bluetooth
    IconCategory.Device, //MonitorHeart
    IconCategory.File, //FolderShared
    IconCategory.Editor, //Mode
    IconCategory.Maps, //Diamond
    IconCategory.Device, //GraphicEq
    IconCategory.Social, //PersonAddAlt1
    IconCategory.Maps, //Navigation
    IconCategory.Image, //Audiotrack
    IconCategory.Action, //AlarmOn
    IconCategory.Communication, //ReadMore
    IconCategory.Image, //CameraAlt
    IconCategory.Maps, //LocalGasStation
    IconCategory.Maps, //Train
    IconCategory.Communication, //DocumentScanner
    IconCategory.Action, //ScheduleSend
    IconCategory.Action, //CalendarViewMonth
    IconCategory.Device, //Dvr
    IconCategory.Notification, //DoNotDisturbOn
    IconCategory.Content, //StackedBarChart
    IconCategory.Action, //Maximize
    IconCategory.Communication, //MoreTime
    IconCategory.Action, //SettingsEthernet
    IconCategory.Content, //SquareFoot
    IconCategory.Editor, //ModeComment
    IconCategory.Action, //ThumbsUpDown
    IconCategory.File, //CloudDone
    IconCategory.Content, //Markunread
    IconCategory.Action, //BookmarkAdd
    IconCategory.Maps, //LocalParking
    IconCategory.Maps, //PersonPinCircle
    IconCategory.Action, //Theaters
    IconCategory.Maps, //LocalFlorist
    IconCategory.Maps, //Factory
    IconCategory.Av, //SortByAlpha
    IconCategory.Action, //ViewAgenda
    IconCategory.Navigation, //SubdirectoryArrowRight
    IconCategory.Action, //ThumbDownOffAlt
    IconCategory.Communication, //MarkEmailUnread
    IconCategory.Social, //ConnectWithoutContact
    IconCategory.Social, //SentimentNeutral
    IconCategory.Editor, //Functions
    IconCategory.Social, //ThumbDownAlt
    IconCategory.Places, //AllInclusive
    IconCategory.Hardware, //KeyboardDoubleArrowDown
)

private fun getCategory14(): List<IconCategory> = listOf(
    IconCategory.Communication, //CallEnd
    IconCategory.Places, //Grass
    IconCategory.Notification, //Wc
    IconCategory.Social, //WavingHand
    IconCategory.Social, //RealEstateAgent
    IconCategory.Places, //AirportShuttle
    IconCategory.Social, //BackHand
    IconCategory.Action, //ImportantDevices
    IconCategory.Social, //Hiking
    IconCategory.File, //CloudQueue
    IconCategory.Maps, //Money
    IconCategory.Maps, //LocalPostOffice
    IconCategory.Search, //Podcasts
    IconCategory.Social, //Architecture
    IconCategory.Action, //Unpublished
    IconCategory.Social, //NotificationsOff
    IconCategory.Maps, //TwoWheeler
    IconCategory.Communication, //ClearAll
    IconCategory.Maps, //Directions
    IconCategory.File, //Workspaces
    IconCategory.Action, //SystemUpdateAlt
    IconCategory.Device, //Nightlight
    IconCategory.Editor, //InsertLink
    IconCategory.Action, //Opacity
    IconCategory.Action, //OpenInBrowser
    IconCategory.Action, //Commute
    IconCategory.Hardware, //Mouse
    IconCategory.Av, //FastRewind
    IconCategory.Action, //ShoppingCartCheckout
    IconCategory.Device, //SportsScore
    IconCategory.Action, //InvertColors
    IconCategory.Social, //Luggage
    IconCategory.Action, //NoAccounts
    IconCategory.Social, //Masks
    IconCategory.Places, //ChildCare
    IconCategory.Search, //Coffee
    IconCategory.Action, //Addchart
    IconCategory.Editor, //ModeEditOutline
    IconCategory.Image, //ColorLens
    IconCategory.Action, //HistoryToggleOff
    IconCategory.Image, //GridOn
    IconCategory.Av, //MicNone
    IconCategory.Editor, //HorizontalRule
    IconCategory.Image, //RotateRight
    IconCategory.Device, //AccessTime
    IconCategory.Maps, //AddBusiness
    IconCategory.Maps, //Route
    IconCategory.Image, //Timelapse
    IconCategory.Image, //CropFree
    IconCategory.Editor, //InsertInvitation
)

private fun getCategory15(): List<IconCategory> = listOf(
    IconCategory.Image, //CurrencyRupee
    IconCategory.Action, //ViewWeek
    IconCategory.Av, //LibraryMusic
    IconCategory.Image, //VideoCameraFront
    IconCategory.Maps, //ElectricalServices
    IconCategory.Social, //FrontHand
    IconCategory.File, //Topic
    IconCategory.Hardware, //DeveloperBoard
    IconCategory.Search, //Shower
    IconCategory.Editor, //FormatAlignLeft
    IconCategory.Social, //Vaccines
    IconCategory.Maps, //Traffic
    IconCategory.Maps, //Warehouse
    IconCategory.Hardware, //KeyboardVoice
    IconCategory.Action, //Tour
    IconCategory.Search, //Yard
    IconCategory.Action, //YoutubeSearchedFor
    IconCategory.Editor, //FormatItalic
    IconCategory.Maps, //DirectionsBoat
    IconCategory.Editor, //FormatColorFill
    IconCategory.Notification, //More
    IconCategory.Places, //BeachAccess
    IconCategory.Action, //HideSource
    IconCategory.Action, //SearchOff
    IconCategory.Hardware, //Start
    IconCategory.Content, //AddLink
    IconCategory.Maps, //LocalBar
    IconCategory.Image, //Slideshow
    IconCategory.Image, //Landscape
    IconCategory.Action, //FilterAltOff
    IconCategory.Action, //NotStarted
    IconCategory.Av, //VolumeDown
    IconCategory.File, //Approval
    IconCategory.Notification, //Power
    IconCategory.Toggle, //StarPurple500
    IconCategory.Action, //BookmarkAdded
    IconCategory.Maps, //AltRoute
    IconCategory.Device, //Water
    IconCategory.Hardware, //Router
    IconCategory.Action, //Shop
    IconCategory.Communication, //Dialpad
    IconCategory.Maps, //Agriculture
    IconCategory.Social, //MoodBad
    IconCategory.Action, //MarkAsUnread
    IconCategory.Action, //Plagiarism
    IconCategory.Maps, //Beenhere
    IconCategory.Image, //PanoramaFishEye
    IconCategory.File, //DownloadDone
    IconCategory.Action, //AssignmentReturn
    IconCategory.Action, //Balance
)

private fun getCategory16(): List<IconCategory> = listOf(
    IconCategory.Maps, //Emergency
    IconCategory.Action, //SettingsInputAntenna
    IconCategory.Places, //Pool
    IconCategory.Content, //Stream
    IconCategory.Editor, //AddComment
    IconCategory.Image, //CropSquare
    IconCategory.Av, //VideocamOff
    IconCategory.Content, //CopyAll
    IconCategory.Image, //CollectionsBookmark
    IconCategory.Image, //LooksTwo
    IconCategory.Content, //DynamicFeed
    IconCategory.Action, //FlightLand
    IconCategory.Action, //TurnedIn
    IconCategory.Av, //RecentActors
    IconCategory.Social, //Compost
    IconCategory.Action, //HotelClass
    IconCategory.Content, //MoveToInbox
    IconCategory.Content, //WhereToVote
    IconCategory.File, //CloudOff
    IconCategory.Image, //Lens
    IconCategory.Hardware, //VideogameAsset
    IconCategory.Maps, //PedalBike
    IconCategory.Social, //EmojiNature
    IconCategory.Action, //AssignmentLate
    IconCategory.Device, //ShareLocation
    IconCategory.Social, //SwitchAccount
    IconCategory.Maps, //_360
    IconCategory.Social, //Diversity3
    IconCategory.Notification, //DoNotDisturb
    IconCategory.Action, //DonutSmall
    IconCategory.Places, //Kitchen
    IconCategory.Device, //GppMaybe
    IconCategory.Places, //Casino
    IconCategory.Action, //Contactless
    IconCategory.Action, //HighlightAlt
    IconCategory.Action, //Rocket
    IconCategory.Action, //SavedSearch
    IconCategory.Action, //SettingsInputComponent
    IconCategory.Content, //Waves
    IconCategory.Editor, //InsertChart
    IconCategory.Av, //WebAsset
    IconCategory.Notification, //SyncProblem
    IconCategory.Maps, //Liquor
    IconCategory.Av, //LibraryAddCheck
    IconCategory.Places, //HolidayVillage
    IconCategory.Action, //ViewCarousel
    IconCategory.Hardware, //KeyboardDoubleArrowUp
    IconCategory.Action, //ViewQuilt
    IconCategory.File, //FileOpen
    IconCategory.Action, //AllInbox
)

private fun getCategory17(): List<IconCategory> = listOf(
    IconCategory.Av, //Hearing
    IconCategory.Action, //SettingsRemote
    IconCategory.Communication, //PhoneEnabled
    IconCategory.Av, //QueueMusic
    IconCategory.Action, //Anchor
    IconCategory.Action, //HourglassFull
    IconCategory.Social, //NightsStay
    IconCategory.Editor, //LinearScale
    IconCategory.Action, //EditOff
    IconCategory.Content, //ContentPasteSearch
    IconCategory.Action, //Mediation
    IconCategory.Action, //FitScreen
    IconCategory.Social, //Interests
    IconCategory.File, //DriveFileMove
    IconCategory.Action, //TurnedInNot
    IconCategory.Action, //Terminal
    IconCategory.Action, //RemoveShoppingCart
    IconCategory.Device, //Cable
    IconCategory.Action, //Flaky
    IconCategory.Social, //KingBed
    IconCategory.Image, //Looks3
    IconCategory.Editor, //StackedLineChart
    IconCategory.Content, //Unarchive
    IconCategory.Av, //PauseCircleFilled
    IconCategory.Notification, //TimeToLeave
    IconCategory.Av, //PauseCircleOutline
    IconCategory.Social, //CatchingPokemon
    IconCategory.Device, //LocationSearching
    IconCategory.Av, //FiberNew
    IconCategory.Editor, //FormatSize
    IconCategory.Av, //Subtitles
    IconCategory.Action, //Toll
    IconCategory.Maps, //Moving
    IconCategory.Hardware, //CastForEducation
    IconCategory.Av, //Note
    IconCategory.Action, //LockReset
    IconCategory.Hardware, //DeviceHub
    IconCategory.Maps, //LocalAirport
    IconCategory.Action, //ViewSidebar
    IconCategory.Device, //Cameraswitch
    IconCategory.Action, //SwapHorizontalCircle
    IconCategory.Action, //LockClock
    IconCategory.Image, //Compare
    IconCategory.Communication, //MarkChatUnread
    IconCategory.Device, //Discount
    IconCategory.Maps, //Sailing
    IconCategory.Editor, //MoneyOff
    IconCategory.Image, //FilterVintage
    IconCategory.Communication, //CancelPresentation
    IconCategory.Content, //ReplyAll
)

private fun getCategory18(): List<IconCategory> = listOf(
    IconCategory.Editor, //InsertComment
    IconCategory.Places, //RoomService
    IconCategory.Editor, //FormatUnderlined
    IconCategory.Places, //Roofing
    IconCategory.Editor, //VerticalAlignBottom
    IconCategory.Action, //VerticalSplit
    IconCategory.Communication, //_3p
    IconCategory.Maps, //AddLocationAlt
    IconCategory.Av, //AvTimer
    IconCategory.Editor, //BubbleChart
    IconCategory.Action, //SettingsVoice
    IconCategory.Device, //Shortcut
    IconCategory.Content, //SelectAll
    IconCategory.Av, //Album
    IconCategory.Action, //OnlinePrediction
    IconCategory.Action, //EventSeat
    IconCategory.Device, //AirplaneTicket
    IconCategory.Action, //DataExploration
    IconCategory.Hardware, //Headset
    IconCategory.Image, //FilterDrama
    IconCategory.Image, //ImageSearch
    IconCategory.Search, //Window
    IconCategory.Action, //NextPlan
    IconCategory.Device, //Radar
    IconCategory.Device, //Wallpaper
    IconCategory.Social, //SportsBasketball
    IconCategory.Editor, //Height
    IconCategory.Maps, //LocalDining
    IconCategory.Device, //DeviceThermostat
    IconCategory.File, //DriveFolderUpload
    IconCategory.Communication, //CallMade
    IconCategory.Hardware, //LaptopMac
    IconCategory.Maps, //MapsUgc
    IconCategory.Action, //RestoreFromTrash
    IconCategory.Action, //PregnantWoman
    IconCategory.Image, //Healing
    IconCategory.Maps, //LocalTaxi
    IconCategory.Device, //GppBad
    IconCategory.Editor, //Schema
    IconCategory.File, //FileDownloadDone
    IconCategory.Image, //RotateLeft
    IconCategory.Av, //PlaylistPlay
    IconCategory.Action, //CameraEnhance
    IconCategory.Maps, //LocalLaundryService
    IconCategory.Content, //LowPriority
    IconCategory.Image, //CenterFocusStrong
    IconCategory.Maps, //TripOrigin
    IconCategory.Device, //DataUsage
    IconCategory.Editor, //VerticalAlignTop
    IconCategory.Places, //RoomPreferences
)

private fun getCategory19(): List<IconCategory> = listOf(
    IconCategory.Social, //NotificationAdd
    IconCategory.Hardware, //Cast
    IconCategory.Av, //Queue
    IconCategory.Action, //ViewStream
    IconCategory.Action, //Token
    IconCategory.File, //CloudSync
    IconCategory.Action, //DynamicForm
    IconCategory.Maps, //DirectionsBusFilled
    IconCategory.Action, //RequestPage
    IconCategory.Notification, //DoDisturbOn
    IconCategory.Maps, //RamenDining
    IconCategory.Action, //Tab
    IconCategory.Action, //MarkunreadMailbox
    IconCategory.Toggle, //StarBorderPurple500
    IconCategory.Image, //Assistant
    IconCategory.Image, //AutoAwesomeMotion
    IconCategory.Action, //CalendarViewWeek
    IconCategory.Image, //BlurOn
    IconCategory.Device, //MonitorWeight
    IconCategory.Av, //Games
    IconCategory.Av, //Radio
    IconCategory.Image, //Crop
    IconCategory.Maps, //LocalDrink
    IconCategory.Av, //ReplayCircleFilled
    IconCategory.Content, //SaveAs
    IconCategory.Maps, //LocalPrintshop
    IconCategory.Maps, //Hail
    IconCategory.Communication, //ScreenShare
    IconCategory.Notification, //VpnLock
    IconCategory.Social, //CrueltyFree
    IconCategory.Home, //SensorDoor
    IconCategory.Maps, //TheaterComedy
    IconCategory.Image, //WbIncandescent
    IconCategory.Image, //FaceRetouchingNatural
    IconCategory.Device, //SignalWifi4Bar
    IconCategory.Action, //SmartButton
    IconCategory.Action, //RemoveDone
    IconCategory.Maps, //Forest
    IconCategory.Places, //SportsBar
    IconCategory.Content, //TextFormat
    IconCategory.Action, //AccessibleForward
    IconCategory.Av, //BrandingWatermark
    IconCategory.Communication, //CallSplit
    IconCategory.Hardware, //Watch
    IconCategory.Action, //SettingsPower
    IconCategory.Maps, //LocalPizza
    IconCategory.Alert, //AddAlert
    IconCategory.Editor, //Square
    IconCategory.Device, //DeveloperMode
    IconCategory.Image, //BrokenImage
)

private fun getCategory20(): List<IconCategory> = listOf(
    IconCategory.Editor, //FormatAlignCenter
    IconCategory.Action, //DensityMedium
    IconCategory.Places, //FreeBreakfast
    IconCategory.Social, //Man
    IconCategory.Alert, //AutoDelete
    IconCategory.Action, //AddToDrive
    IconCategory.Social, //SportsKabaddi
    IconCategory.Image, //Flare
    IconCategory.Action, //AddCard
    IconCategory.Av, //Forward10
    IconCategory.Places, //EscalatorWarning
    IconCategory.Image, //WbCloudy
    IconCategory.Action, //Try
    IconCategory.Social, //Sports
    IconCategory.Hardware, //TabletMac
    IconCategory.Image, //Cases
    IconCategory.Action, //Outbox
    IconCategory.Maps, //NotListedLocation
    IconCategory.Home, //ElectricBolt
    IconCategory.Device, //ModeNight
    IconCategory.Action, //WorkHistory
    IconCategory.Image, //FilterNone
    IconCategory.Places, //Bathtub
    IconCategory.Notification, //RunningWithErrors
    IconCategory.Content, //FontDownload
    IconCategory.Maps, //TransferWithinAStation
    IconCategory.Image, //Colorize
    IconCategory.Social, //ReduceCapacity
    IconCategory.Social, //EmojiFoodBeverage
    IconCategory.Action, //CardTravel
    IconCategory.Hardware, //DevicesOther
    IconCategory.Device, //WifiTethering
    IconCategory.Social, //Sick
    IconCategory.Maps, //AddLocation
    IconCategory.Action, //OfflinePin
    IconCategory.Maps, //DinnerDining
    IconCategory.Social, //EmojiSymbols
    IconCategory.Content, //Weekend
    IconCategory.Places, //ChildFriendly
    IconCategory.Action, //Fax
    IconCategory.Image, //AutoFixNormal
    IconCategory.Notification, //EnhancedEncryption
    IconCategory.Notification, //FolderSpecial
    IconCategory.Device, //Bloodtype
    IconCategory.Editor, //FormatPaint
    IconCategory.Navigation, //LegendToggle
    IconCategory.Editor, //AreaChart
    IconCategory.Image, //CropOriginal
    IconCategory.Maps, //BakeryDining
    IconCategory.Device, //BatteryStd
)

private fun getCategory21(): List<IconCategory> = listOf(
    IconCategory.Hardware, //DesktopMac
    IconCategory.Av, //Replay10
    IconCategory.Image, //FilterCenterFocus
    IconCategory.Social, //EmojiTransportation
    IconCategory.Action, //FindReplace
    IconCategory.Social, //HeartBroken
    IconCategory.Action, //Compress
    IconCategory.Action, //AssignmentReturned
    IconCategory.Search, //Light
    IconCategory.Search, //DoorFront
    IconCategory.Social, //Diversity1
    IconCategory.Action, //AssuredWorkload
    IconCategory.Action, //CalendarViewDay
    IconCategory.Social, //Cookie
    IconCategory.Image, //Brightness4
    IconCategory.Action, //Rowing
    IconCategory.Content, //HowToVote
    IconCategory.Action, //ChromeReaderMode
    IconCategory.Action, //_123
    IconCategory.Social, //Wallet
    IconCategory.Action, //GeneratingTokens
    IconCategory.Action, //Outlet
    IconCategory.Social, //SportsTennis
    IconCategory.Action, //Http
    IconCategory.Maps, //WineBar
    IconCategory.Image, //NaturePeople
    IconCategory.Maps, //Terrain
    IconCategory.Action, //FreeCancellation
    IconCategory.Image, //Dehaze
    IconCategory.Search, //Garage
    IconCategory.Action, //NewLabel
    IconCategory.Social, //AddReaction
    IconCategory.Maps, //MultipleStop
    IconCategory.Navigation, //SouthEast
    IconCategory.Content, //Upcoming
    IconCategory.Device, //Lan
    IconCategory.File, //AttachEmail
    IconCategory.Action, //SettingsBrightness
    IconCategory.Editor, //FormatColorText
    IconCategory.Content, //Gesture
    IconCategory.Social, //Woman
    IconCategory.Action, //BackupTable
    IconCategory.Social, //PersonalInjury
    IconCategory.Image, //Photo
    IconCategory.Social, //Elderly
    IconCategory.Action, //Spellcheck
    IconCategory.Editor, //FormatAlignRight
    IconCategory.Communication, //Unsubscribe
    IconCategory.Image, //FlashOff
    IconCategory.Action, //RestorePage
)

private fun getCategory22(): List<IconCategory> = listOf(
    IconCategory.Action, //AlarmAdd
    IconCategory.Social, //AddModerator
    IconCategory.Places, //Foundation
    IconCategory.Action, //EventRepeat
    IconCategory.Social, //Scale
    IconCategory.Action, //CreditCardOff
    IconCategory.Action, //PanToolAlt
    IconCategory.Editor, //ScatterPlot
    IconCategory.Social, //Transgender
    IconCategory.Action, //NoiseControlOff
    IconCategory.Hardware, //KeyboardTab
    IconCategory.Action, //WifiProtectedSetup
    IconCategory.Social, //OutdoorGrill
    IconCategory.Navigation, //AppSettingsAlt
    IconCategory.Action, //DisplaySettings
    IconCategory.Action, //PlayForWork
    IconCategory.Image, //TagFaces
    IconCategory.Action, //DisabledVisible
    IconCategory.Maps, //TakeoutDining
    IconCategory.Social, //Deck
    IconCategory.Device, //SignalCellular4Bar
    IconCategory.Navigation, //SubdirectoryArrowLeft
    IconCategory.Editor, //FormatListNumberedRtl
    IconCategory.Image, //AutoAwesomeMosaic
    IconCategory.Navigation, //AssistantDirection
    IconCategory.Action, //ManageHistory
    IconCategory.Hardware, //LaptopChromebook
    IconCategory.Image, //Brightness6
    IconCategory.Action, //SettingsOverscan
    IconCategory.Maps, //StoreMallDirectory
    IconCategory.Editor, //DataObject
    IconCategory.Social, //FollowTheSigns
    IconCategory.Content, //Attribution
    IconCategory.Image, //Brightness1
    IconCategory.Action, //ViewTimeline
    IconCategory.Hardware, //Phonelink
    IconCategory.Places, //FoodBank
    IconCategory.Social, //PlusOne
    IconCategory.Image, //Details
    IconCategory.Image, //Brightness5
    IconCategory.Image, //Grain
    IconCategory.Social, //SocialDistance
    IconCategory.Av, //ClosedCaption
    IconCategory.Device, //FmdBad
    IconCategory.Editor, //Highlight
    IconCategory.Action, //Outbound
    IconCategory.Device, //Splitscreen
    IconCategory.Image, //FlipCameraAndroid
    IconCategory.Maps, //Icecream
    IconCategory.Communication, //CoPresent
)

private fun getCategory23(): List<IconCategory> = listOf(
    IconCategory.Device, //FlashlightOn
    IconCategory.Notification, //DoDisturb
    IconCategory.Maps, //Museum
    IconCategory.Action, //SwitchAccessShortcut
    IconCategory.Communication, //DomainVerification
    IconCategory.Image, //Flip
    IconCategory.Navigation, //NorthWest
    IconCategory.Hardware, //Monitor
    IconCategory.Image, //ViewComfy
    IconCategory.Action, //CancelScheduleSend
    IconCategory.Social, //Fireplace
    IconCategory.Action, //SwapVerticalCircle
    IconCategory.Places, //Gite
    IconCategory.Action, //Gif
    IconCategory.Maps, //Nightlife
    IconCategory.Editor, //FormatAlignJustify
    IconCategory.Notification, //SmsFailed
    IconCategory.Maps, //LocalPharmacy
    IconCategory.Places, //Villa
    IconCategory.Communication, //PresentToAll
    IconCategory.Action, //Webhook
    IconCategory.Device, //NetworkWifi
    IconCategory.Action, //SatelliteAlt
    IconCategory.Navigation, //WaterfallChart
    IconCategory.Device, //SimCardDownload
    IconCategory.Navigation, //SwitchLeft
    IconCategory.Av, //VideoSettings
    IconCategory.Action, //SettingsInputComposite
    IconCategory.Image, //Loupe
    IconCategory.Av, //HighQuality
    IconCategory.Social, //Pix
    IconCategory.Action, //Quickreply
    IconCategory.Maps, //Hardware
    IconCategory.Image, //ImageNotSupported
    IconCategory.Notification, //NetworkCheck
    IconCategory.Communication, //MarkChatRead
    IconCategory.Notification, //PhoneCallback
    IconCategory.Places, //NightShelter
    IconCategory.Action, //ViewDay
    IconCategory.Maps, //DepartureBoard
    IconCategory.Social, //CleanHands
    IconCategory.Communication, //AddIcCall
    IconCategory.Maps, //SetMeal
    IconCategory.Action, //CommentBank
    IconCategory.Action, //Troubleshoot
    IconCategory.Device, //AccessTimeFilled
    IconCategory.Maps, //AddRoad
    IconCategory.Device, //AirplanemodeActive
    IconCategory.File, //RuleFolder
    IconCategory.Device, //MobileFriendly
)

private fun getCategory24(): List<IconCategory> = listOf(
    IconCategory.Image, //Bedtime
    IconCategory.Action, //LineWeight
    IconCategory.Social, //Piano
    IconCategory.Search, //Dining
    IconCategory.Maps, //EvStation
    IconCategory.Content, //FlagCircle
    IconCategory.File, //FolderZip
    IconCategory.Device, //Usb
    IconCategory.Image, //FlipCameraIos
    IconCategory.Action, //HorizontalSplit
    IconCategory.Image, //Filter1
    IconCategory.Communication, //PhonelinkRing
    IconCategory.Social, //SportsMotorsports
    IconCategory.Places, //GolfCourse
    IconCategory.Social, //Surfing
    IconCategory.Editor, //MergeType
    IconCategory.Social, //Sanitizer
    IconCategory.Social, //PsychologyAlt
    IconCategory.Notification, //Adb
    IconCategory.Av, //FeaturedPlayList
    IconCategory.Social, //Groups2
    IconCategory.Device, //SendToMobile
    IconCategory.Search, //Flatware
    IconCategory.File, //FolderCopy
    IconCategory.Notification, //PhoneForwarded
    IconCategory.Notification, //PowerOff
    IconCategory.Communication, //CallReceived
    IconCategory.Action, //Output
    IconCategory.Action, //PictureInPicture
    IconCategory.Action, //Polymer
    IconCategory.Action, //BatchPrediction
    IconCategory.Editor, //AddChart
    IconCategory.Maps, //ElectricCar
    IconCategory.Hardware, //Speaker
    IconCategory.Notification, //SystemUpdate
    IconCategory.Device, //BatteryAlert
    IconCategory.Social, //Hive
    IconCategory.Communication, //StayCurrentPortrait
    IconCategory.Maps, //MedicalInformation
    IconCategory.Social, //SportsHandball
    IconCategory.Action, //SendAndArchive
    IconCategory.Image, //AddToPhotos
    IconCategory.Maps, //LocalSee
    IconCategory.Image, //MovieCreation
    IconCategory.Content, //ContentPasteGo
    IconCategory.Image, //Looks4
    IconCategory.Action, //Html
    IconCategory.Maps, //Festival
    IconCategory.Social, //SportsBaseball
    IconCategory.Action, //CodeOff
)

private fun getCategory25(): List<IconCategory> = listOf(
    IconCategory.Action, //BookmarkRemove
    IconCategory.Maps, //Plumbing
    IconCategory.Notification, //PersonalVideo
    IconCategory.Device, //LensBlur
    IconCategory.Av, //PlaylistAddCheckCircle
    IconCategory.Image, //Animation
    IconCategory.Hardware, //Toys
    IconCategory.Action, //SettingsBluetooth
    IconCategory.Image, //Panorama
    IconCategory.Image, //CenterFocusWeak
    IconCategory.Editor, //Numbers
    IconCategory.Device, //ScreenSearchDesktop
    IconCategory.Image, //MovieFilter
    IconCategory.Search, //CoffeeMaker
    IconCategory.Social, //EditNotifications
    IconCategory.Maps, //CarRental
    IconCategory.Hardware, //Gamepad
    IconCategory.Places, //NoPhotography
    IconCategory.Navigation, //SouthWest
    IconCategory.File, //CloudCircle
    IconCategory.Maps, //LayersClear
    IconCategory.Editor, //FormatShapes
    IconCategory.Device, //SignalWifiStatusbar4Bar
    IconCategory.Hardware, //SimCard
    IconCategory.Places, //Stairs
    IconCategory.Maps, //Attractions
    IconCategory.Device, //ScreenRotation
    IconCategory.Av, //ControlCamera
    IconCategory.Communication, //PhonelinkLock
    IconCategory.Maps, //ZoomInMap
    IconCategory.Av, //PlaylistRemove
    IconCategory.Action, //ShopTwo
    IconCategory.Search, //Blender
    IconCategory.Search, //TableRestaurant
    IconCategory.Action, //FlipToFront
    IconCategory.Device, //SignalWifiStatusbarConnectedNoInternet4
    IconCategory.Social, //SportsVolleyball
    IconCategory.Image, //CropDin
    IconCategory.Maps, //EditLocation
    IconCategory.Home, //EnergySavingsLeaf
    IconCategory.Communication, //CellTower
    IconCategory.Navigation, //PivotTableChart
    IconCategory.Places, //Microwave
    IconCategory.Maps, //PestControl
    IconCategory.Image, //CurrencyBitcoin
    IconCategory.Places, //Backpack
    IconCategory.Hardware, //KeyboardAlt
    IconCategory.Communication, //PhoneDisabled
    IconCategory.Device, //GpsNotFixed
    IconCategory.Social, //Diversity2
)

private fun getCategory26(): List<IconCategory> = listOf(
    IconCategory.Action, //GifBox
    IconCategory.Communication, //RingVolume
    IconCategory.Maps, //LocalConvenienceStore
    IconCategory.Action, //SpeakerNotesOff
    IconCategory.File, //Difference
    IconCategory.Image, //CurrencyYen
    IconCategory.Image, //LeakAdd
    IconCategory.Action, //Eject
    IconCategory.Image, //ControlPointDuplicate
    IconCategory.Image, //Brightness7
    IconCategory.Social, //Pages
    IconCategory.Image, //Filter
    IconCategory.Navigation, //SwitchRight
    IconCategory.Image, //ViewCompact
    IconCategory.Maps, //RunCircle
    IconCategory.Notification, //VoiceChat
    IconCategory.Device, //SystemSecurityUpdateGood
    IconCategory.Content, //FilterListOff
    IconCategory.Maps, //Church
    IconCategory.Image, //IncompleteCircle
    IconCategory.Image, //Nature
    IconCategory.Notification, //Vibration
    IconCategory.Maps, //DryCleaning
    IconCategory.Notification, //AirlineSeatReclineNormal
    IconCategory.Communication, //LocationOff
    IconCategory.File, //SnippetFolder
    IconCategory.Social, //SportsFootball
    IconCategory.Editor, //MoneyOffCsred
    IconCategory.Action, //AlarmOff
    IconCategory.Action, //PermDataSetting
    IconCategory.Maps, //EditRoad
    IconCategory.Action, //SwitchAccessShortcutAdd
    IconCategory.Maps, //EditAttributes
    IconCategory.Action, //SettingsInputHdmi
    IconCategory.Communication, //PhonelinkSetup
    IconCategory.Image, //Texture
    IconCategory.Maps, //EditLocationAlt
    IconCategory.Search, //BedroomParent
    IconCategory.Av, //SlowMotionVideo
    IconCategory.Av, //AddToQueue
    IconCategory.Device, //BluetoothConnected
    IconCategory.Action, //HourglassDisabled
    IconCategory.Notification, //DoDisturbAlt
    IconCategory.Content, //NextWeek
    IconCategory.Action, //PermScanWifi
    IconCategory.Editor, //PieChartOutline
    IconCategory.Device, //Battery5Bar
    IconCategory.Hardware, //ConnectedTv
    IconCategory.Search, //BedroomBaby
    IconCategory.Home, //SensorWindow
)

private fun getCategory27(): List<IconCategory> = listOf(
    IconCategory.Editor, //FormatIndentIncrease
    IconCategory.Editor, //MoveUp
    IconCategory.Image, //TimerOff
    IconCategory.Search, //CameraIndoor
    IconCategory.Device, //Nfc
    IconCategory.Action, //SensorsOff
    IconCategory.Communication, //Duo
    IconCategory.Home, //AutoMode
    IconCategory.Image, //Contrast
    IconCategory.Action, //WorkOff
    IconCategory.Social, //DownhillSkiing
    IconCategory.Editor, //ShortText
    IconCategory.Social, //GroupRemove
    IconCategory.Places, //Elevator
    IconCategory.Social, //Kayaking
    IconCategory.Device, //RememberMe
    IconCategory.Maps, //CarRepair
    IconCategory.Image, //PhotoSizeSelectActual
    IconCategory.Image, //Transform
    IconCategory.Home, //SolarPower
    IconCategory.Social, //Co2
    IconCategory.Action, //JoinFull
    IconCategory.Image, //VideoCameraBack
    IconCategory.Action, //PictureInPictureAlt
    IconCategory.Action, //AppBlocking
    IconCategory.Search, //Bathroom
    IconCategory.Social, //PublicOff
    IconCategory.Maps, //WrongLocation
    IconCategory.Action, //SettingsCell
    IconCategory.Av, //RepeatOne
    IconCategory.Device, //ModeStandby
    IconCategory.Maps, //Moped
    IconCategory.Action, //Abc
    IconCategory.Social, //SingleBed
    IconCategory.Places, //Wash
    IconCategory.Action, //Javascript
    IconCategory.Social, //RemoveModerator
    IconCategory.Communication, //SwapCalls
    IconCategory.Search, //DoorSliding
    IconCategory.Places, //SmokingRooms
    IconCategory.Search, //ChairAlt
    IconCategory.Device, //Pattern
    IconCategory.Communication, //StayPrimaryPortrait
    IconCategory.Maps, //LocalMovies
    IconCategory.Action, //LineStyle
    IconCategory.Notification, //DoNotDisturbAlt
    IconCategory.Action, //PermDeviceInformation
    IconCategory.Social, //Boy
    IconCategory.Image, //Looks5
    IconCategory.Av, //Airplay
)

private fun getCategory28(): List<IconCategory> = listOf(
    IconCategory.Device, //BrightnessHigh
    IconCategory.Action, //LightbulbCircle
    IconCategory.Action, //AppShortcut
    IconCategory.Editor, //FormatColorReset
    IconCategory.Maps, //DirectionsBoatFilled
    IconCategory.Social, //NotificationsPaused
    IconCategory.Hardware, //TabletAndroid
    IconCategory.Image, //MotionPhotosOn
    IconCategory.Social, //DomainAdd
    IconCategory.Places, //Cabin
    IconCategory.Places, //HouseSiding
    IconCategory.Maps, //Satellite
    IconCategory.Search, //CameraOutdoor
    IconCategory.Editor, //StrikethroughS
    IconCategory.Social, //Skateboarding
    IconCategory.Maps, //Signpost
    IconCategory.Places, //HotTub
    IconCategory.Maps, //SoupKitchen
    IconCategory.Av, //CallToAction
    IconCategory.Action, //UpdateDisabled
    IconCategory.Action, //SubtitlesOff
    IconCategory.Hardware, //CastConnected
    IconCategory.Image, //Rotate90DegreesCcw
    IconCategory.Action, //SwipeLeft
    IconCategory.Editor, //VerticalAlignCenter
    IconCategory.Device, //BatterySaver
    IconCategory.Search, //DoorBack
    IconCategory.Communication, //Voicemail
    IconCategory.Notification, //SyncDisabled
    IconCategory.Social, //PersonRemoveAlt1
    IconCategory.Editor, //AlignHorizontalLeft
    IconCategory.Places, //Countertops
    IconCategory.Social, //Fitbit
    IconCategory.Search, //Living
    IconCategory.Device, //PlayLesson
    IconCategory.Image, //PhotoCameraFront
    IconCategory.Av, //Snooze
    IconCategory.Editor, //Hexagon
    IconCategory.Social, //SafetyDivider
    IconCategory.Hardware, //LaptopWindows
    IconCategory.Image, //MicExternalOn
    IconCategory.Maps, //Tram
    IconCategory.Device, //DataSaverOff
    IconCategory.Action, //PrivateConnectivity
    IconCategory.Av, //Hd
    IconCategory.Image, //WbTwilight
    IconCategory.Maps, //TaxiAlert
    IconCategory.Action, //ArrowOutward
    IconCategory.Action, //VoiceOverOff
    IconCategory.Editor, //Rectangle
)

private fun getCategory29(): List<IconCategory> = listOf(
    IconCategory.Device, //Storm
    IconCategory.Image, //CurrencyPound
    IconCategory.Navigation, //AppsOutage
    IconCategory.Maps, //BreakfastDining
    IconCategory.Maps, //Merge
    IconCategory.Hardware, //BrowserUpdated
    IconCategory.Image, //Gradient
    IconCategory.File, //FileDownloadOff
    IconCategory.Av, //Replay30
    IconCategory.Device, //DataSaverOn
    IconCategory.Hardware, //DeviceUnknown
    IconCategory.Places, //FireExtinguisher
    IconCategory.Search, //Doorbell
    IconCategory.Maps, //CrisisAlert
    IconCategory.Device, //BrightnessMedium
    IconCategory.Device, //BluetoothSearching
    IconCategory.Social, //Thunderstorm
    IconCategory.Notification, //TapAndPlay
    IconCategory.Av, //RepeatOn
    IconCategory.Places, //WaterDamage
    IconCategory.Action, //JoinInner
    IconCategory.Places, //Carpenter
    IconCategory.Device, //Grid4x4
    IconCategory.Maps, //Straight
    IconCategory.Device, //SsidChart
    IconCategory.Content, //ContentPasteOff
    IconCategory.Device, //SignalWifi0Bar
    IconCategory.Places, //RvHookup
    IconCategory.Places, //ChargingStation
    IconCategory.Editor, //MoveDown
    IconCategory.Device, //BrightnessLow
    IconCategory.Av, //ClosedCaptionOff
    IconCategory.Action, //InstallDesktop
    IconCategory.Places, //BabyChangingStation
    IconCategory.Image, //AssistantPhoto
    IconCategory.Action, //SwipeRight
    IconCategory.Navigation, //OfflineShare
    IconCategory.Maps, //Subway
    IconCategory.Device, //BluetoothDisabled
    IconCategory.Social, //GroupOff
    IconCategory.Search, //TableBar
    IconCategory.Device, //AdUnits
    IconCategory.Device, //MobiledataOff
    IconCategory.Device, //Screenshot
    IconCategory.Search, //BedroomChild
    IconCategory.Device, //Battery4Bar
    IconCategory.Maps, //Atm
    IconCategory.Places, //Soap
    IconCategory.Notification, //NoEncryption
    IconCategory.Device, //NetworkCell
)

private fun getCategory30(): List<IconCategory> = listOf(
    IconCategory.Image, //HideImage
    IconCategory.Action, //SettingsInputSvideo
    IconCategory.Action, //SwipeUp
    IconCategory.Social, //SportsCricket
    IconCategory.Social, //Groups3
    IconCategory.Device, //Battery0Bar
    IconCategory.Notification, //SdCard
    IconCategory.Editor, //MultilineChart
    IconCategory.Social, //SportsMartialArts
    IconCategory.Image, //ExposurePlus1
    IconCategory.Communication, //CallMerge
    IconCategory.Social, //SportsMma
    IconCategory.Action, //FlipToBack
    IconCategory.Image, //MusicOff
    IconCategory.Device, //WifiCalling3
    IconCategory.Image, //Crop169
    IconCategory.Device, //HdrAuto
    IconCategory.Maps, //TransitEnterexit
    IconCategory.Home, //ShieldMoon
    IconCategory.Notification, //PhoneMissed
    IconCategory.Action, //ViewArray
    IconCategory.Maps, //BrunchDining
    IconCategory.Hardware, //KeyboardHide
    IconCategory.Communication, //PhonelinkErase
    IconCategory.Image, //Exposure
    IconCategory.Image, //ThermostatAuto
    IconCategory.Action, //OpenInNewOff
    IconCategory.Communication, //MobileScreenShare
    IconCategory.Image, //Filter2
    IconCategory.Device, //SecurityUpdateGood
    IconCategory.Places, //SmokeFree
    IconCategory.Device, //BatteryUnknown
    IconCategory.Av, //FeaturedVideo
    IconCategory.Image, //ShutterSpeed
    IconCategory.Editor, //Polyline
    IconCategory.Image, //PhotoAlbum
    IconCategory.Action, //DensitySmall
    IconCategory.Editor, //Score
    IconCategory.Social, //SportsGolf
    IconCategory.Maps, //Hvac
    IconCategory.Social, //NordicWalking
    IconCategory.Social, //Girl
    IconCategory.Maps, //ConnectingAirports
    IconCategory.Places, //Umbrella
    IconCategory.Image, //FilterTiltShift
    IconCategory.Editor, //TextIncrease
    IconCategory.Action, //AllOut
    IconCategory.Hardware, //Scanner
    IconCategory.Editor, //BorderAll
    IconCategory.Av, //AudioFile
)

private fun getCategory31(): List<IconCategory> = listOf(
    IconCategory.Av, //ShuffleOn
    IconCategory.Action, //Shop2
    IconCategory.Maps, //ElectricBike
    IconCategory.Content, //WebStories
    IconCategory.Social, //Face6
    IconCategory.File, //FolderDelete
    IconCategory.Device, //Battery6Bar
    IconCategory.Social, //SportsGymnastics
    IconCategory.Maps, //DirectionsTransit
    IconCategory.Device, //SignalWifiOff
    IconCategory.Action, //LabelOff
    IconCategory.Image, //Looks6
    IconCategory.Notification, //AirlineSeatReclineExtra
    IconCategory.Action, //DataThresholding
    IconCategory.Image, //Looks
    IconCategory.Image, //HdrStrong
    IconCategory.Maps, //Egg
    IconCategory.Device, //SettingsSystemDaydream
    IconCategory.Image, //Brightness3
    IconCategory.Hardware, //Tablet
    IconCategory.Av, //Forward30
    IconCategory.Maps, //SafetyCheck
    IconCategory.Av, //InterpreterMode
    IconCategory.Image, //LinkedCamera
    IconCategory.Image, //Vrpano
    IconCategory.Social, //Paragliding
    IconCategory.Av, //PlaylistAddCircle
    IconCategory.Editor, //FormatIndentDecrease
    IconCategory.Av, //_5g
    IconCategory.Places, //DoNotTouch
    IconCategory.Action, //LockPerson
    IconCategory.Places, //Tapas
    IconCategory.Action, //TabUnselected
    IconCategory.Image, //CropPortrait
    IconCategory.Action, //Commit
    IconCategory.Image, //BlurCircular
    IconCategory.Maps, //ElectricScooter
    IconCategory.Communication, //PersonAddDisabled
    IconCategory.Communication, //DomainDisabled
    IconCategory.Av, //MusicVideo
    IconCategory.Action, //RoundedCorner
    IconCategory.Device, //Battery3Bar
    IconCategory.Places, //RiceBowl
    IconCategory.Social, //Face3
    IconCategory.Image, //FlashAuto
    IconCategory.Maps, //Stadium
    IconCategory.File, //DriveFileMoveRtl
    IconCategory.Device, //SignalWifiBad
    IconCategory.Maps, //ModeOfTravel
    IconCategory.Maps, //BusAlert
)

private fun getCategory32(): List<IconCategory> = listOf(
    IconCategory.Places, //Tty
    IconCategory.Social, //PartyMode
    IconCategory.Av, //QueuePlayNext
    IconCategory.Image, //PhotoFilter
    IconCategory.Places, //Fence
    IconCategory.Device, //AccessAlarms
    IconCategory.Maps, //LocalCarWash
    IconCategory.Communication, //ContactEmergency
    IconCategory.Editor, //FormatClear
    IconCategory.Maps, //LocalHotel
    IconCategory.Av, //Replay5
    IconCategory.Editor, //SpaceBar
    IconCategory.Image, //MotionPhotosAuto
    IconCategory.Social, //Snowboarding
    IconCategory.Action, //ViewKanban
    IconCategory.Communication, //Spoke
    IconCategory.Social, //_6FtApart
    IconCategory.Av, //VideoFile
    IconCategory.Communication, //CallMissedOutgoing
    IconCategory.Action, //TextRotateVertical
    IconCategory.Places, //Balcony
    IconCategory.Image, //Iso
    IconCategory.Communication, //SpeakerPhone
    IconCategory.Action, //InstallMobile
    IconCategory.Editor, //FormatLineSpacing
    IconCategory.Communication, //DesktopAccessDisabled
    IconCategory.Social, //Kitesurfing
    IconCategory.Device, //SignalWifiConnectedNoInternet4
    IconCategory.Image, //Brightness2
    IconCategory.Editor, //CandlestickChart
    IconCategory.Maps, //Castle
    IconCategory.Places, //Houseboat
    IconCategory.Action, //ExploreOff
    IconCategory.Places, //NoFood
    IconCategory.Image, //Crop75
    IconCategory.Image, //Rotate90DegreesCw
    IconCategory.Communication, //MarkUnreadChatAlt
    IconCategory.Image, //PhotoSizeSelectSmall
    IconCategory.Editor, //HorizontalDistribute
    IconCategory.Action, //SpatialAudioOff
    IconCategory.Communication, //CellWifi
    IconCategory.Content, //ReportOff
    IconCategory.Image, //Tonality
    IconCategory.Action, //Css
    IconCategory.Image, //FilterHdr
    IconCategory.Home, //OilBarrel
    IconCategory.Editor, //AlignVerticalBottom
    IconCategory.Action, //SwipeDown
    IconCategory.Home, //WindPower
    IconCategory.Places, //Bento
)

private fun getCategory33(): List<IconCategory> = listOf(
    IconCategory.Action, //TextRotationNone
    IconCategory.Device, //AccessAlarm
    IconCategory.Av, //ArtTrack
    IconCategory.Home, //SensorOccupied
    IconCategory.Places, //WheelchairPickup
    IconCategory.Image, //CurrencyRuble
    IconCategory.Image, //ExposureZero
    IconCategory.Device, //Aod
    IconCategory.Device, //Battery1Bar
    IconCategory.Notification, //ImagesearchRoller
    IconCategory.Image, //CropRotate
    IconCategory.Av, //HearingDisabled
    IconCategory.Communication, //StopScreenShare
    IconCategory.Maps, //CarCrash
    IconCategory.Device, //FlashlightOff
    IconCategory.Image, //PhotoSizeSelectLarge
    IconCategory.Device, //SignalCellular0Bar
    IconCategory.Av, //Forward5
    IconCategory.Notification, //Mms
    IconCategory.Communication, //PrintDisabled
    IconCategory.Editor, //AlignHorizontalCenter
    IconCategory.Image, //Filter3
    IconCategory.Action, //JoinLeft
    IconCategory.Action, //NotAccessible
    IconCategory.Places, //Iron
    IconCategory.Hardware, //SpeakerGroup
    IconCategory.Social, //Snowshoeing
    IconCategory.Device, //AddToHomeScreen
    IconCategory.Device, //SignalWifiStatusbarNull
    IconCategory.Action, //NoiseAware
    IconCategory.Social, //SouthAmerica
    IconCategory.Device, //SecurityUpdate
    IconCategory.Device, //GpsOff
    IconCategory.Action, //PinInvoke
    IconCategory.Action, //Pinch
    IconCategory.Device, //PunchClock
    IconCategory.Maps, //Streetview
    IconCategory.Home, //ElectricMeter
    IconCategory.Image, //HdrWeak
    IconCategory.Communication, //CallMissed
    IconCategory.Hardware, //Earbuds
    IconCategory.Places, //Bungalow
    IconCategory.Editor, //VerticalDistribute
    IconCategory.Image, //CameraFront
    IconCategory.Image, //Crop54
    IconCategory.Social, //SportsHockey
    IconCategory.Social, //IceSkating
    IconCategory.Action, //SwipeVertical
    IconCategory.Social, //ElderlyWoman
    IconCategory.Av, //Explicit
)

private fun getCategory34(): List<IconCategory> = listOf(
    IconCategory.Editor, //AlignHorizontalRight
    IconCategory.Hardware, //KeyboardCapslock
    IconCategory.Device, //SdStorage
    IconCategory.Action, //ExtensionOff
    IconCategory.Home, //HeatPump
    IconCategory.Editor, //FormatStrikethrough
    IconCategory.Communication, //PausePresentation
    IconCategory.Maps, //Mosque
    IconCategory.Action, //PermCameraMic
    IconCategory.Editor, //Superscript
    IconCategory.Social, //SportsRugby
    IconCategory.Action, //ViewCozy
    IconCategory.Image, //BurstMode
    IconCategory.Device, //Grid3x3
    IconCategory.Editor, //DataArray
    IconCategory.Image, //FilterFrames
    IconCategory.Device, //ResetTv
    IconCategory.Social, //Person2
    IconCategory.Device, //_4gMobiledata
    IconCategory.Av, //VideoLabel
    IconCategory.Maps, //DirectionsSubway
    IconCategory.Action, //JoinRight
    IconCategory.Av, //_4k
    IconCategory.Maps, //TurnRight
    IconCategory.Hardware, //HeadsetOff
    IconCategory.Social, //Scoreboard
    IconCategory.Communication, //CommentsDisabled
    IconCategory.Av, //FiberSmartRecord
    IconCategory.Maps, //CompassCalibration
    IconCategory.Places, //Crib
    IconCategory.Device, //Dataset
    IconCategory.Device, //BrightnessAuto
    IconCategory.Editor, //Margin
    IconCategory.Communication, //DialerSip
    IconCategory.Maps, //ElectricRickshaw
    IconCategory.Action, //PinEnd
    IconCategory.Image, //LogoDev
    IconCategory.Social, //Face2
    IconCategory.Notification, //SyncLock
    IconCategory.Image, //CameraRoll
    IconCategory.Places, //Chalet
    IconCategory.Action, //SwipeRightAlt
    IconCategory.Communication, //InvertColorsOff
    IconCategory.Maps, //AirlineStops
    IconCategory.Notification, //DiscFull
    IconCategory.Device, //SignalCellularConnectedNoInternet4Bar
    IconCategory.Device, //Battery2Bar
    IconCategory.Notification, //NoEncryptionGmailerrorred
    IconCategory.Social, //Face4
    IconCategory.Device, //WifiLock
)

private fun getCategory35(): List<IconCategory> = listOf(
    IconCategory.Device, //ScreenshotMonitor
    IconCategory.Social, //Sledding
    IconCategory.Content, //Deselect
    IconCategory.Communication, //WifiCalling
    IconCategory.Image, //BlurLinear
    IconCategory.Device, //DoNotDisturbOnTotalSilence
    IconCategory.Editor, //Pentagon
    IconCategory.Image, //FilterBAndW
    IconCategory.Communication, //Rtt
    IconCategory.Image, //CropLandscape
    IconCategory.Image, //Crop32
    IconCategory.Device, //NearbyError
    IconCategory.Home, //GasMeter
    IconCategory.Notification, //BluetoothAudio
    IconCategory.Device, //AirplanemodeInactive
    IconCategory.Device, //Phishing
    IconCategory.Device, //_1xMobiledata
    IconCategory.Communication, //PortableWifiOff
    IconCategory.Maps, //ForkRight
    IconCategory.Places, //DoNotStep
    IconCategory.Device, //SecurityUpdateWarning
    IconCategory.Editor, //WrapText
    IconCategory.Maps, //DirectionsRailway
    IconCategory.Hardware, //KeyboardCommandKey
    IconCategory.Notification, //SdCardAlert
    IconCategory.Editor, //AlignVerticalTop
    IconCategory.Communication, //SendTimeExtension
    IconCategory.Communication, //MailLock
    IconCategory.Av, //RepeatOneOn
    IconCategory.Maps, //NoCrash
    IconCategory.Maps, //NoMeals
    IconCategory.Places, //NoMeetingRoom
    IconCategory.Image, //SwitchCamera
    IconCategory.Editor, //Subscript
    IconCategory.Editor, //BorderClear
    IconCategory.Editor, //AlignVerticalCenter
    IconCategory.Action, //BrowseGallery
    IconCategory.Device, //SignalCellularConnectedNoInternet0Bar
    IconCategory.Editor, //TextDecrease
    IconCategory.Image, //SwitchVideo
    IconCategory.Notification, //SimCardAlert
    IconCategory.Action, //Php
    IconCategory.Action, //ViewComfyAlt
    IconCategory.File, //FolderOff
    IconCategory.Action, //TextRotateUp
    IconCategory.Places, //Escalator
    IconCategory.Image, //Filter7
    IconCategory.Maps, //RailwayAlert
    IconCategory.Action, //TextRotationAngledown
    IconCategory.Content, //FontDownloadOff
)

private fun getCategory36(): List<IconCategory> = listOf(
    IconCategory.Image, //Filter4
    IconCategory.Places, //Dry
    IconCategory.Device, //ScreenLockPortrait
    IconCategory.Social, //SignLanguage
    IconCategory.Action, //TextRotationAngleup
    IconCategory.Notification, //DoNotDisturbOff
    IconCategory.Image, //Filter9Plus
    IconCategory.Maps, //ElectricMoped
    IconCategory.Device, //WifiPassword
    IconCategory.Av, //SurroundSound
    IconCategory.Action, //TextRotationDown
    IconCategory.Image, //ExposurePlus2
    IconCategory.Av, //ClosedCaptionDisabled
    IconCategory.Av, //RemoveFromQueue
    IconCategory.Notification, //AirlineSeatIndividualSuite
    IconCategory.Action, //AddHome
    IconCategory.Hardware, //HomeMax
    IconCategory.Notification, //PhonePaused
    IconCategory.Image, //WbIridescent
    IconCategory.Maps, //TurnLeft
    IconCategory.Action, //UnfoldMoreDouble
    IconCategory.Image, //GridOff
    IconCategory.Maps, //LocalPlay
    IconCategory.Places, //Stroller
    IconCategory.Navigation, //AddHomeWork
    IconCategory.Action, //ViewCompactAlt
    IconCategory.Av, //PlayDisabled
    IconCategory.Editor, //BorderStyle
    IconCategory.Device, //SystemSecurityUpdateWarning
    IconCategory.Action, //NetworkPing
    IconCategory.Maps, //UTurnLeft
    IconCategory.Device, //SystemSecurityUpdate
    IconCategory.Device, //WifiTetheringOff
    IconCategory.Av, //WebAssetOff
    IconCategory.Image, //MotionPhotosPaused
    IconCategory.Image, //PhotoCameraBack
    IconCategory.Social, //Cyclone
    IconCategory.Action, //SwipeDownAlt
    IconCategory.Image, //MonochromePhotos
    IconCategory.Communication, //StayCurrentLandscape
    IconCategory.Image, //AutoFixOff
    IconCategory.Maps, //Airlines
    IconCategory.Hardware, //Dock
    IconCategory.Hardware, //HeadphonesBattery
    IconCategory.Image, //Filter5
    IconCategory.Communication, //Sip
    IconCategory.Device, //EdgesensorHigh
    IconCategory.Maps, //PestControlRodent
    IconCategory.Hardware, //PowerInput
    IconCategory.Hardware, //SmartScreen
)

private fun getCategory37(): List<IconCategory> = listOf(
    IconCategory.Maps, //EggAlt
    IconCategory.Action, //OnDeviceTraining
    IconCategory.Notification, //DoDisturbOff
    IconCategory.Places, //NoDrinks
    IconCategory.Communication, //Nat
    IconCategory.Image, //ExposureNeg1
    IconCategory.Av, //Lyrics
    IconCategory.Communication, //KeyOff
    IconCategory.Notification, //AirlineSeatFlat
    IconCategory.Maps, //BikeScooter
    IconCategory.Editor, //Padding
    IconCategory.Notification, //PhoneLocked
    IconCategory.Maps, //TireRepair
    IconCategory.Action, //DensityLarge
    IconCategory.Hardware, //BrowserNotSupported
    IconCategory.Notification, //NetworkLocked
    IconCategory.Image, //FaceRetouchingOff
    IconCategory.Editor, //BorderOuter
    IconCategory.Social, //Face5
    IconCategory.Social, //Person4
    IconCategory.Av, //Sd
    IconCategory.Device, //NetworkWifi1Bar
    IconCategory.Action, //SpatialTracking
    IconCategory.Maps, //NearMeDisabled
    IconCategory.Communication, //StayPrimaryLandscape
    IconCategory.Editor, //LineAxis
    IconCategory.Device, //SignalCellularNodata
    IconCategory.Maps, //Snowmobile
    IconCategory.Action, //SwipeLeftAlt
    IconCategory.Device, //_30fps
    IconCategory.Home, //PropaneTank
    IconCategory.Communication, //NoSim
    IconCategory.Maps, //Sos
    IconCategory.Hardware, //EarbudsBattery
    IconCategory.Device, //SignalCellularOff
    IconCategory.Device, //WifiFind
    IconCategory.Device, //_4gPlusMobiledata
    IconCategory.Maps, //DirectionsTransitFilled
    IconCategory.Social, //Person3
    IconCategory.Maps, //MinorCrash
    IconCategory.Device, //SignalWifi4BarLock
    IconCategory.Device, //LteMobiledata
    IconCategory.Device, //AddAlarm
    IconCategory.Device, //NetworkWifi3Bar
    IconCategory.Image, //LeakRemove
    IconCategory.Action, //SpatialAudio
    IconCategory.Device, //LocationDisabled
    IconCategory.Image, //PanoramaPhotosphere
    IconCategory.Device, //SignalCellularNull
    IconCategory.Av, //MissedVideoCall
)

private fun getCategory38(): List<IconCategory> = listOf(
    IconCategory.Editor, //InsertPageBreak
    IconCategory.Device, //MobileOff
    IconCategory.Image, //Filter8
    IconCategory.Hardware, //PhonelinkOff
    IconCategory.Action, //SwipeUpAlt
    IconCategory.Image, //Filter9
    IconCategory.Device, //BluetoothDrive
    IconCategory.Social, //Flood
    IconCategory.Av, //_10k
    IconCategory.Social, //NoLuggage
    IconCategory.Maps, //KebabDining
    IconCategory.Maps, //NoTransfer
    IconCategory.Image, //Timer10
    IconCategory.Device, //MediaBluetoothOn
    IconCategory.Maps, //FlightClass
    IconCategory.Hardware, //HomeMini
    IconCategory.Image, //VideoStable
    IconCategory.Image, //Filter6
    IconCategory.Maps, //Fort
    IconCategory.Hardware, //AdfScanner
    IconCategory.Home, //ModeFanOff
    IconCategory.Maps, //DirectionsSubwayFilled
    IconCategory.Maps, //FireTruck
    IconCategory.Image, //RawOn
    IconCategory.Image, //BlurOff
    IconCategory.Image, //Deblur
    IconCategory.Image, //MotionPhotosOff
    IconCategory.Image, //WbShade
    IconCategory.Device, //Rsvp
    IconCategory.Maps, //TempleBuddhist
    IconCategory.Maps, //EmergencyShare
    IconCategory.Image, //MotionPhotosPause
    IconCategory.Communication, //VpnKeyOff
    IconCategory.Maps, //DirectionsRailwayFilled
    IconCategory.Notification, //TvOff
    IconCategory.Image, //Vignette
    IconCategory.Device, //EdgesensorLow
    IconCategory.Hardware, //DeveloperBoardOff
    IconCategory.Device, //GridGoldenratio
    IconCategory.Notification, //PhoneBluetoothSpeaker
    IconCategory.Image, //HdrOn
    IconCategory.Notification, //AirlineSeatFlatAngled
    IconCategory.Device, //UsbOff
    IconCategory.Device, //_3gMobiledata
    IconCategory.Social, //ScubaDiving
    IconCategory.Av, //FiberPin
    IconCategory.Image, //PanoramaHorizontal
    IconCategory.Device, //NetworkWifi2Bar
    IconCategory.Image, //DirtyLens
    IconCategory.Device, //ScreenLockRotation
)

private fun getCategory39(): List<IconCategory> = listOf(
    IconCategory.Image, //ImageAspectRatio
    IconCategory.Places, //NoCell
    IconCategory.Device, //DatasetLinked
    IconCategory.Image, //_30fpsSelect
    IconCategory.Device, //_60fps
    IconCategory.Device, //ScreenLockLandscape
    IconCategory.Social, //Tsunami
    IconCategory.Social, //SevereCold
    IconCategory.Maps, //UTurnRight
    IconCategory.Social, //PianoOff
    IconCategory.Device, //LtePlusMobiledata
    IconCategory.Device, //SignalCellularAlt1Bar
    IconCategory.Image, //CameraRear
    IconCategory.Device, //Wifi2Bar
    IconCategory.Device, //SignalCellularAlt2Bar
    IconCategory.Device, //Timer10Select
    IconCategory.Image, //CurrencyYuan
    IconCategory.Action, //UnfoldLessDouble
    IconCategory.Image, //CurrencyLira
    IconCategory.Device, //WifiTetheringError
    IconCategory.Hardware, //VideogameAssetOff
    IconCategory.Image, //Timer3
    IconCategory.Image, //_60fpsSelect
    IconCategory.Action, //Repartition
    IconCategory.Notification, //DirectionsOff
    IconCategory.Image, //PanoramaWideAngleSelect
    IconCategory.Notification, //AirlineSeatLegroomNormal
    IconCategory.Maps, //TempleHindu
    IconCategory.Image, //_24mp
    IconCategory.Action, //WidthFull
    IconCategory.Av, //FiberDvr
    IconCategory.Device, //SignalCellularNoSim
    IconCategory.Maps, //ForkLeft
    IconCategory.Editor, //ShapeLine
    IconCategory.Maps, //Synagogue
    IconCategory.Image, //ExposureNeg2
    IconCategory.Maps, //RemoveRoad
    IconCategory.Maps, //ScreenRotationAlt
    IconCategory.Social, //RollerSkating
    IconCategory.Social, //Tornado
    IconCategory.Notification, //AirlineSeatLegroomExtra
    IconCategory.Home, //RollerShades
    IconCategory.Maps, //TurnSharpRight
    IconCategory.Places, //NoFlash
    IconCategory.Editor, //BorderInner
    IconCategory.Av, //_4kPlus
    IconCategory.Image, //AutofpsSelect
    IconCategory.Device, //Wifi1Bar
    IconCategory.Action, //WidthNormal
    IconCategory.Editor, //BorderLeft
)

private fun getCategory40(): List<IconCategory> = listOf(
    IconCategory.Notification, //AirlineSeatLegroomReduced
    IconCategory.Device, //WifiChannel
    IconCategory.Maps, //RoundaboutRight
    IconCategory.Device, //GMobiledata
    IconCategory.Av, //_1k
    IconCategory.Editor, //BorderBottom
    IconCategory.Action, //Transcribe
    IconCategory.Editor, //FormatTextdirectionLToR
    IconCategory.Social, //AssistWalker
    IconCategory.Maps, //TurnSlightRight
    IconCategory.Social, //Man2
    IconCategory.Social, //Landslide
    IconCategory.Social, //Woman2
    IconCategory.Hardware, //KeyboardControlKey
    IconCategory.Editor, //BorderVertical
    IconCategory.Action, //WidthWide
    IconCategory.Device, //Timer3Select
    IconCategory.Places, //NoBackpack
    IconCategory.Maps, //TurnSlightLeft
    IconCategory.Image, //PanoramaHorizontalSelect
    IconCategory.Av, //_2k
    IconCategory.Editor, //BorderHorizontal
    IconCategory.Image, //PanoramaPhotosphereSelect
    IconCategory.Image, //PanoramaWideAngle
    IconCategory.Image, //WbAuto
    IconCategory.Social, //Blind
    IconCategory.Editor, //FormatTextdirectionRToL
    IconCategory.Image, //HdrPlus
    IconCategory.Device, //HMobiledata
    IconCategory.Image, //PanoramaVerticalSelect
    IconCategory.Av, //_1kPlus
    IconCategory.Editor, //BorderTop
    IconCategory.Image, //MicExternalOff
    IconCategory.Editor, //BorderRight
    IconCategory.Social, //_18UpRating
    IconCategory.Home, //Propane
    IconCategory.Home, //BroadcastOnPersonal
    IconCategory.Places, //NoStroller
    IconCategory.Home, //Blinds
    IconCategory.Device, //MediaBluetoothOff
    IconCategory.Av, //_8k
    IconCategory.Social, //Volcano
    IconCategory.Device, //EMobiledata
    IconCategory.Image, //CurrencyFranc
    IconCategory.Device, //RMobiledata
    IconCategory.Image, //_12mp
    IconCategory.Action, //HlsOff
    IconCategory.Action, //Hls
    IconCategory.Image, //PanoramaVertical
    IconCategory.Places, //VapingRooms
)

private fun getCategory41(): List<IconCategory> = listOf(
    IconCategory.Image, //Mp
    IconCategory.Home, //RollerShadesClosed
    IconCategory.Device, //HPlusMobiledata
    IconCategory.Maps, //EmergencyRecording
    IconCategory.Image, //HdrEnhancedSelect
    IconCategory.Av, //_5k
    IconCategory.Notification, //VideoChat
    IconCategory.Social, //NoAdultContent
    IconCategory.Av, //_8kPlus
    IconCategory.Hardware, //WatchOff
    IconCategory.Av, //_9kPlus
    IconCategory.File, //FormatOverline
    IconCategory.Image, //Hevc
    IconCategory.Places, //Desk
    IconCategory.Device, //HdrOnSelect
    IconCategory.Hardware, //KeyboardOptionKey
    IconCategory.Av, //_3k
    IconCategory.Home, //BlindsClosed
    IconCategory.Home, //Curtains
    IconCategory.Image, //BedtimeOff
    IconCategory.Maps, //RoundaboutLeft
    IconCategory.Image, //_18mp
    IconCategory.Maps, //TurnSharpLeft
    IconCategory.Image, //_10mp
    IconCategory.Home, //VerticalShades
    IconCategory.Home, //VerticalShadesClosed
    IconCategory.Home, //BroadcastOnHome
    IconCategory.Device, //HdrAutoSelect
    IconCategory.Home, //CurtainsClosed
    IconCategory.Home, //NestCamWiredStand
    IconCategory.Av, //_5kPlus
    IconCategory.Image, //_23mp
    IconCategory.Image, //RawOff
    IconCategory.Av, //_7k
    IconCategory.Device, //NearbyOff
    IconCategory.Av, //_9k
    IconCategory.Av, //_3kPlus
    IconCategory.Device, //DevicesFold
    IconCategory.Av, //_2kPlus
    IconCategory.Image, //HdrOff
    IconCategory.Av, //_6k
    IconCategory.Av, //_7kPlus
    IconCategory.Av, //_6kPlus
    IconCategory.Device, //HdrOffSelect
    IconCategory.Image, //_11mp
    IconCategory.Image, //_20mp
    IconCategory.Image, //_3mp
    IconCategory.Places, //VapeFree
    IconCategory.Image, //_5mp
    IconCategory.Image, //_16mp
)

private fun getCategory42(): List<IconCategory> = listOf(
    IconCategory.Image, //_13mp
    IconCategory.Image, //_15mp
    IconCategory.Image, //_21mp
    IconCategory.Image, //_2mp
    IconCategory.Editor, //TypeSpecimen
    IconCategory.Image, //_17mp
    IconCategory.Image, //_22mp
    IconCategory.Image, //_14mp
    IconCategory.Image, //_19mp
    IconCategory.Image, //_8mp
    IconCategory.Image, //_4mp
    IconCategory.Image, //_9mp
    IconCategory.Image, //_6mp
    IconCategory.Image, //_7mp
    IconCategory.Device, //Fluorescent
    IconCategory.Social, //Man4
    IconCategory.Maps, //RampLeft
    IconCategory.Maps, //RampRight
    IconCategory.Social, //Man3
    IconCategory.Maps, //FireHydrantAlt
    IconCategory.Device, //MacroOff
)